// multi_horizon_bench.cpp — P2-S1-5: the multi-horizon driver compute profile.
//
// Micro-benchmarks the S1 capstone driver (risk::MultiHorizonOptimizer) on two paths:
//
//   * BM_MultiHorizonMinimal  — the MINIMAL-constraint DISPATCH path (GrossNet +
//     PositionCap only ⇒ the as-built PortfolioOptimizer inner solve, NO ADMM). This is
//     the R7 reduction path and the cheap per-rebalance cost.
//   * BM_MultiHorizonAugmented — the AUGMENTED path (FactorExposure + BetaNeutral added
//     ⇒ the S1-2 ConstrainedQpSolver ADMM). The expensive constrained book.
//
// Both sweep a small grid (N ∈ {200,500,1000}, K ∈ {5,10}, H ∈ {1,3}); N is kept modest
// so the suite finishes in seconds even in Debug. rebalances/sec is reported via
// SetItemsProcessed (one rebalance == one run() over a single-period schedule). A third
// bench (BM_MultiHorizonAdmmSolve) isolates the time-per-ADMM-solve at the largest N.
//
// DESIGN GUARANTEE reported as counters: the QP consumes V MATRIX-FREE via
// FactorModel::apply (V = X F Xᵀ + D is kept FACTORED, NEVER densified), so the per-solve
// footprint is O(N·K) not O(N²). The observed wall-clock vs N (the {200,500,1000} sweep)
// is the empirical witness; `nk` and `n2` counters print the O(N·K) and O(N²) work units
// so the gap is visible in the table.
//
// stacked_mpc is N/A here: the shipped path is the GP aim-collapse (a true stacked
// multi-period MPC QP is a recorded atx-core lift; cfg.stacked_mpc ⇒ Err(NotImplemented)).
//
// Build is Debug / clang-cl (the project default), so EVERY number here is an UPPER-BOUND
// latency — NOT a release figure. Mirrors the established risk_covariance_bench.cpp /
// cost_bench.cpp pattern (no BENCHMARK_MAIN here — it lives in bench_main.cpp). Synthetic
// data is generated by a seeded Xoshiro256pp (bench scaffold only; the driver is RNG-free).

#include <span>
#include <vector>

#include <benchmark/benchmark.h>

#include <Eigen/Dense>

#include "atx/core/linalg/linalg.hpp" // MatX, VecX
#include "atx/core/random.hpp"        // Xoshiro256pp (synthetic data)
#include "atx/core/types.hpp"         // f64, usize

#include "atx/engine/risk/constraints.hpp"  // ConstraintSet, FactorExposure, BetaNeutral, PositionCap
#include "atx/engine/risk/factor_model.hpp" // FactorModel
#include "atx/engine/risk/horizon.hpp"      // SignalHorizon
#include "atx/engine/risk/multi_horizon.hpp" // MultiHorizonOptimizer, MultiHorizonConfig, HorizonSources
#include "atx/engine/risk/multi_period.hpp"  // RebalanceSchedule, book::CostInputs

namespace {

using atx::f64;
using atx::usize;
using atx::core::Xoshiro256pp;
using atx::core::linalg::MatX;
using atx::core::linalg::VecX;
using atx::engine::book::CostInputs;
using atx::engine::risk::BetaNeutral;
using atx::engine::risk::ConstraintSet;
using atx::engine::risk::FactorExposure;
using atx::engine::risk::FactorModel;
using atx::engine::risk::HorizonSource;
using atx::engine::risk::HorizonSources;
using atx::engine::risk::MultiHorizonConfig;
using atx::engine::risk::MultiHorizonOptimizer;
using atx::engine::risk::PositionCap;
using atx::engine::risk::RebalanceSchedule;
using atx::engine::risk::SignalHorizon;

// ---------------------------------------------------------------------------
//  Synthetic fixture: an N-instrument, K-factor FactorModel + two distinct-horizon
//  alpha sources. Seeded so the per-instrument spread varies; F = I (SPD), D > 0.
// ---------------------------------------------------------------------------
[[nodiscard]] FactorModel make_model(usize n, usize k) {
  Xoshiro256pp rng{0x5151ULL};
  MatX x(static_cast<Eigen::Index>(n), static_cast<Eigen::Index>(k));
  for (usize i = 0; i < n; ++i) {
    for (usize c = 0; c < k; ++c) {
      x(static_cast<Eigen::Index>(i), static_cast<Eigen::Index>(c)) = 0.1 * rng.normal();
    }
  }
  MatX f = MatX::Identity(static_cast<Eigen::Index>(k), static_cast<Eigen::Index>(k));
  VecX d = VecX::Constant(static_cast<Eigen::Index>(n), 0.2);
  auto m = FactorModel::create(std::move(x), std::move(f), std::move(d), 0U, 1U);
  return std::move(*m); // bench fixture — inputs are valid by construction
}

// Two dollar-neutral-able alpha cross-sections, one per source. Seeded, deterministic.
[[nodiscard]] std::vector<f64> make_alpha(usize n, atx::u64 seed) {
  Xoshiro256pp rng{seed};
  std::vector<f64> a(n);
  for (usize i = 0; i < n; ++i) {
    a[i] = rng.normal();
  }
  return a;
}

// A two-source pack with DISTINCT horizons (a slow/persistent + a fast/decaying signal)
// — the real multi-horizon superposition. The spans must outlive run(); the caller owns
// the backing vectors and passes them in.
[[nodiscard]] HorizonSources two_source_pack(std::span<const f64> slow_src,
                                             std::span<const f64> fast_src) {
  HorizonSources hs;
  hs.pairs.emplace_back(slow_src, SignalHorizon{40.0}); // slow decay
  hs.pairs.emplace_back(fast_src, SignalHorizon{1.5});  // fast decay
  return hs;
}

// Minimal constraint set (GrossNet + PositionCap) ⇒ the dispatch path (no ADMM).
[[nodiscard]] MultiHorizonConfig minimal_cfg(usize horizon) {
  MultiHorizonConfig cfg;
  cfg.risk_aversion = 1.0;
  cfg.constraints.gross.gross_leverage = 1.0;
  cfg.constraints.gross.dollar_neutral = true;
  cfg.constraints.pos = PositionCap{1.0};
  cfg.horizon = horizon;
  cfg.trade_rate = 1.0;
  cfg.prox_max_iters = 64U;
  cfg.capacity_bound_gross = true;
  return cfg;
}

// Augmented constraint set (adds FactorExposure on factors 0/1 + BetaNeutral) ⇒ the
// S1-2 ADMM QP path. iters kept modest so the grid finishes in seconds in Debug (a
// feasibility-clearing budget is the R3 test's concern, not the bench's).
[[nodiscard]] MultiHorizonConfig augmented_cfg(usize horizon, std::span<const f64> beta) {
  MultiHorizonConfig cfg = minimal_cfg(horizon);
  cfg.risk_aversion = 0.5;
  cfg.constraints.pos = PositionCap{0.4};
  cfg.constraints.fexp = FactorExposure{{0U, 1U}, {0.2, 0.2}};
  cfg.constraints.beta = BetaNeutral{beta, 0.1};
  cfg.qp.iters = 200U; // bench-only budget (NOT a feasibility-clearing value)
  return cfg;
}

// Report the O(N·K) (matrix-free) vs O(N²) (dense-V) work units as counters so the
// design guarantee (per-solve footprint O(N·K), never O(N²)) is visible per row.
void tag_complexity(benchmark::State &state, usize n, usize k) {
  state.counters["nk"] = static_cast<f64>(n * k);
  state.counters["n2"] = static_cast<f64>(n * n);
  state.SetItemsProcessed(state.iterations()); // one rebalance per iteration ⇒ rebalances/sec
}

// ---------------------------------------------------------------------------
//  BM_MultiHorizonMinimal — the dispatch (PortfolioOptimizer) path. range: (N, K, H).
// ---------------------------------------------------------------------------
void BM_MultiHorizonMinimal(benchmark::State &state) {
  const usize n = static_cast<usize>(state.range(0));
  const usize k = static_cast<usize>(state.range(1));
  const usize h = static_cast<usize>(state.range(2));
  const FactorModel v = make_model(n, k);
  const std::vector<f64> slow = make_alpha(n, 0x1111ULL);
  const std::vector<f64> fast = make_alpha(n, 0x2222ULL);
  const RebalanceSchedule sched{{0U}};
  const CostInputs cost{0.0, 0.0, 1e9};
  const MultiHorizonOptimizer mh{minimal_cfg(h)};

  for (auto _ : state) {
    auto r = mh.run(
        sched, [&](usize) { return two_source_pack(std::span<const f64>(slow), std::span<const f64>(fast)); },
        [&](usize) -> const FactorModel & { return v; }, cost);
    benchmark::DoNotOptimize(r);
    benchmark::ClobberMemory();
  }
  tag_complexity(state, n, k);
}
BENCHMARK(BM_MultiHorizonMinimal)
    ->Args({200, 5, 1})
    ->Args({200, 5, 3})
    ->Args({500, 10, 1})
    ->Args({500, 10, 3})
    ->Args({1000, 10, 1})
    ->Args({1000, 10, 3})
    ->Unit(benchmark::kMicrosecond);

// ---------------------------------------------------------------------------
//  BM_MultiHorizonAugmented — the ADMM QP path. range: (N, K, H).
// ---------------------------------------------------------------------------
void BM_MultiHorizonAugmented(benchmark::State &state) {
  const usize n = static_cast<usize>(state.range(0));
  const usize k = static_cast<usize>(state.range(1));
  const usize h = static_cast<usize>(state.range(2));
  const FactorModel v = make_model(n, k);
  const std::vector<f64> slow = make_alpha(n, 0x1111ULL);
  const std::vector<f64> fast = make_alpha(n, 0x2222ULL);
  const std::vector<f64> beta(n, 1.0); // benign unit beta (length N)
  const RebalanceSchedule sched{{0U}};
  const CostInputs cost{0.0, 0.0, 1e9};
  const MultiHorizonOptimizer mh{augmented_cfg(h, std::span<const f64>(beta))};

  for (auto _ : state) {
    auto r = mh.run(
        sched, [&](usize) { return two_source_pack(std::span<const f64>(slow), std::span<const f64>(fast)); },
        [&](usize) -> const FactorModel & { return v; }, cost);
    benchmark::DoNotOptimize(r);
    benchmark::ClobberMemory();
  }
  tag_complexity(state, n, k);
}
BENCHMARK(BM_MultiHorizonAugmented)
    ->Args({200, 5, 1})
    ->Args({200, 5, 3})
    ->Args({500, 10, 1})
    ->Args({500, 10, 3})
    ->Args({1000, 10, 1})
    ->Args({1000, 10, 3})
    ->Unit(benchmark::kMicrosecond);

// ---------------------------------------------------------------------------
//  BM_MultiHorizonAdmmSolve — time per ADMM solve at the LARGEST N (the augmented
//  path isolated at N=1000, K=10, H=3). One run() == one ADMM solve over a single
//  period, so the per-iteration wall time IS the per-ADMM-solve time at this N.
// ---------------------------------------------------------------------------
void BM_MultiHorizonAdmmSolve(benchmark::State &state) {
  const usize n = 1000U;
  const usize k = 10U;
  const usize h = 3U;
  const FactorModel v = make_model(n, k);
  const std::vector<f64> slow = make_alpha(n, 0x1111ULL);
  const std::vector<f64> fast = make_alpha(n, 0x2222ULL);
  const std::vector<f64> beta(n, 1.0);
  const RebalanceSchedule sched{{0U}};
  const CostInputs cost{0.0, 0.0, 1e9};
  const MultiHorizonOptimizer mh{augmented_cfg(h, std::span<const f64>(beta))};

  for (auto _ : state) {
    auto r = mh.run(
        sched, [&](usize) { return two_source_pack(std::span<const f64>(slow), std::span<const f64>(fast)); },
        [&](usize) -> const FactorModel & { return v; }, cost);
    benchmark::DoNotOptimize(r);
    benchmark::ClobberMemory();
  }
  // stacked_mpc is N/A (recorded lift): the shipped path is the GP aim-collapse. Encoded
  // as a counter so it is visible in the table next to the per-solve time.
  state.counters["stacked_mpc_NA_recorded_lift"] = 1.0;
  tag_complexity(state, n, k);
}
BENCHMARK(BM_MultiHorizonAdmmSolve)->Unit(benchmark::kMillisecond);

} // namespace
