// optimizer_scale_bench.cpp — P2-S8-0: the as-built solver-core SCALE baseline.
//
// This is the perf gate's reference point. It times the AUGMENTED path of
// risk::MultiHorizonOptimizer::run — the dispatch that reaches the S1-2
// ConstrainedQpSolver ADMM (FactorExposure + BetaNeutral added on top of the
// minimal GrossNet+PositionCap set) — over the SCALE sweep the S8.3 perf gate is
// measured against:
//
//     M (instruments) ∈ {500, 1500, 3000, 5000}
//     K (factors)     ∈ {16, 64}
//
// One run() == one ADMM solve over a single-period RebalanceSchedule, so the
// per-iteration wall time IS the per-run augmented-solve time at that (M, K). The
// as-built solver densifies the augmented constraint matrix Ã (qp_solver.hpp:193)
// and runs a fixed 600×50 PCG with a per-solve-rebuilt Jacobi preconditioner, so
// each outer iteration is O(M²) — the ~20 s/run regression that forced the three
// DISABLED_MultiHorizonIntegration tests off at S4. The numbers this bench prints
// are the S8.0 BASELINE: S8.3 must show a >= 20x speedup vs them and a target of
// < 500 ms/run at M=3000, K=64.
//
// Iteration budget: a FIXED, DOCUMENTED small count (iters=4, kkt_iters=4 ⇒ 16 PCG
// matvecs/solve) — NOT the shipped default (iters=600, kkt_iters=50 ⇒ 30,000 matvecs).
// The shipped budget is intractable as a Debug baseline: at iters=80/kkt=20 a single
// M=500 augmented solve already measured ~83 s, and the dense Ã is ~M×3M so the cost
// is O(M²) in M — M=5000 at the shipped budget would be HOURS. The wall time is LINEAR
// in the matvec count, so absolute ms at the shipped budget ≈ measured ms × (30000/16)
// ≈ measured × 1875 (recorded in the ledger). Holding iters FIXED isolates exactly what
// the S8.3 perf gate measures — the PER-ITERATION dense-Ã cost and its O(M²) scaling in
// M — without the iteration count confounding it. S8.3 re-runs THIS bench at THIS SAME
// fixed budget so the >=20x speedup comparison is apples-to-apples (the rewrite's win is
// the per-iteration matvec going O(M²)→O(M·K²), not fewer iterations). Each case runs
// exactly once (->Iterations(1)); the reported wall-clock per (M, K) is the ledger number.
// The fixed budget is kBaselineIters / kBaselineKktIters below.
//
// Build is Debug / clang-cl (the project default), so EVERY number is an UPPER-
// BOUND latency — NOT a release figure; the S8.3 comparison is apples-to-apples
// (same preset, same bench). Mirrors multi_horizon_bench.cpp (no BENCHMARK_MAIN
// here — it lives in bench_main.cpp). Synthetic data is generated by a seeded
// Xoshiro256pp (bench scaffold only; the driver is RNG-free).

#include <span>
#include <vector>

#include <benchmark/benchmark.h>

#include <Eigen/Dense>

#include "atx/core/linalg/linalg.hpp" // MatX, VecX
#include "atx/core/random.hpp"        // Xoshiro256pp (synthetic data)
#include "atx/core/types.hpp"         // f64, usize

#include "atx/engine/risk/constraints.hpp"   // ConstraintSet, FactorExposure, BetaNeutral, PositionCap
#include "atx/engine/risk/factor_model.hpp"  // FactorModel
#include "atx/engine/risk/horizon.hpp"       // SignalHorizon
#include "atx/engine/risk/multi_horizon.hpp" // MultiHorizonOptimizer, MultiHorizonConfig, HorizonSources
#include "atx/engine/risk/multi_period.hpp"  // RebalanceSchedule, book::CostInputs

namespace {

using atx::f64;
using atx::usize;
using atx::core::Xoshiro256pp;
using atx::core::linalg::MatX;
using atx::core::linalg::VecX;
using atx::engine::book::CostInputs;
using atx::engine::risk::BetaNeutral;
using atx::engine::risk::FactorExposure;
using atx::engine::risk::FactorModel;
using atx::engine::risk::HorizonSources;
using atx::engine::risk::MultiHorizonConfig;
using atx::engine::risk::MultiHorizonOptimizer;
using atx::engine::risk::PositionCap;
using atx::engine::risk::RebalanceSchedule;
using atx::engine::risk::SignalHorizon;

// FIXED baseline ADMM budget (NOT the shipped iters=600/kkt_iters=50) — see the file
// header note: a modest fixed count so the M∈{500..5000} sweep completes, while the
// dense-Ã code path and its O(M²)-in-M scaling are exactly the as-built ones. S8.3
// re-runs at THIS budget so the >=20x speedup comparison is apples-to-apples.
constexpr atx::usize kBaselineIters = 4U;    // FIXED outer ADMM (NOT shipped 600)
constexpr atx::usize kBaselineKktIters = 4U; // FIXED inner PCG  (NOT shipped 50)

// ---------------------------------------------------------------------------
//  Synthetic fixture: an M-instrument, K-factor FactorModel + two distinct-horizon
//  alpha sources. Seeded so the per-instrument spread varies; F = I (SPD), D > 0.
// ---------------------------------------------------------------------------
[[nodiscard]] FactorModel make_model(usize m, usize k) {
  Xoshiro256pp rng{0x5151ULL};
  MatX x(static_cast<Eigen::Index>(m), static_cast<Eigen::Index>(k));
  for (usize i = 0; i < m; ++i) {
    for (usize c = 0; c < k; ++c) {
      x(static_cast<Eigen::Index>(i), static_cast<Eigen::Index>(c)) = 0.1 * rng.normal();
    }
  }
  MatX f = MatX::Identity(static_cast<Eigen::Index>(k), static_cast<Eigen::Index>(k));
  VecX d = VecX::Constant(static_cast<Eigen::Index>(m), 0.2);
  auto model = FactorModel::create(std::move(x), std::move(f), std::move(d), 0U, 1U);
  return std::move(*model); // bench fixture — inputs are valid by construction
}

// One dollar-neutral-able alpha cross-section. Seeded, deterministic.
[[nodiscard]] std::vector<f64> make_alpha(usize m, atx::u64 seed) {
  Xoshiro256pp rng{seed};
  std::vector<f64> a(m);
  for (usize i = 0; i < m; ++i) {
    a[i] = rng.normal();
  }
  return a;
}

// A two-source pack with DISTINCT horizons (a slow/persistent + a fast/decaying
// signal). The spans must outlive run(); the caller owns the backing vectors.
[[nodiscard]] HorizonSources two_source_pack(std::span<const f64> slow_src,
                                             std::span<const f64> fast_src) {
  HorizonSources hs;
  hs.pairs.emplace_back(slow_src, SignalHorizon{40.0}); // slow decay
  hs.pairs.emplace_back(fast_src, SignalHorizon{1.5});  // fast decay
  return hs;
}

// Augmented constraint set (GrossNet + PositionCap + FactorExposure on factors 0/1
// + BetaNeutral) ⇒ the S1-2 ADMM QP path that reaches ConstrainedQpSolver. The
// iteration budget is a FIXED modest count (see kBaselineIters note above) so the
// sweep completes; the dense-Ã code path and its O(M²) scaling are unchanged.
[[nodiscard]] MultiHorizonConfig augmented_cfg(std::span<const f64> beta) {
  MultiHorizonConfig cfg;
  cfg.risk_aversion = 0.5;
  cfg.constraints.gross.gross_leverage = 1.0;
  cfg.constraints.gross.dollar_neutral = true;
  cfg.constraints.pos = PositionCap{0.4};
  cfg.constraints.fexp = FactorExposure{{0U, 1U}, {0.2, 0.2}};
  cfg.constraints.beta = BetaNeutral{beta, 0.1};
  cfg.horizon = 1U;     // single forward step — the per-run augmented-solve cost
  cfg.trade_rate = 1.0; // full first-move step
  cfg.qp.iters = kBaselineIters;        // FIXED baseline budget (not shipped 600)
  cfg.qp.kkt_iters = kBaselineKktIters; // FIXED baseline budget (not shipped 50)
  // rho=1, sigma=1e-6, feas_tol=1e-6 left at shipped defaults.
  return cfg;
}

// ---------------------------------------------------------------------------
//  BM_OptimizerScaleAugmented — the augmented ADMM QP path at scale. range:(M, K).
//  One run() == one densified-Ã ADMM solve; the per-iteration wall time IS the
//  per-run augmented-solve time. ->Unit(kMillisecond) so the table is readable at
//  the multi-second large end; ->UseRealTime so we measure wall-clock, not CPU.
// ---------------------------------------------------------------------------
void BM_OptimizerScaleAugmented(benchmark::State &state) {
  const usize m = static_cast<usize>(state.range(0));
  const usize k = static_cast<usize>(state.range(1));
  const FactorModel v = make_model(m, k);
  const std::vector<f64> slow = make_alpha(m, 0x1111ULL);
  const std::vector<f64> fast = make_alpha(m, 0x2222ULL);
  const std::vector<f64> beta(m, 1.0); // benign unit beta (length M)
  const RebalanceSchedule sched{{0U}};
  const CostInputs cost{0.0, 0.0, 1e9};
  const MultiHorizonOptimizer mh{augmented_cfg(std::span<const f64>(beta))};

  for (auto _ : state) {
    auto r = mh.run(
        sched, [&](usize) { return two_source_pack(std::span<const f64>(slow), std::span<const f64>(fast)); },
        [&](usize) -> const FactorModel & { return v; }, cost);
    benchmark::DoNotOptimize(r);
    benchmark::ClobberMemory();
  }
  // O(M·K) (matrix-free V) vs O(M²) (dense Ã) work units — the dense-Ã defect made
  // visible per row: the as-built per-iteration cost tracks n2, not mk.
  state.counters["mk"] = static_cast<f64>(m * k);
  state.counters["m2"] = static_cast<f64>(m * m);
  state.SetItemsProcessed(state.iterations()); // one augmented solve per iteration
}
BENCHMARK(BM_OptimizerScaleAugmented)
    ->Args({500, 16})
    ->Args({500, 64})
    ->Args({1500, 16})
    ->Args({1500, 64})
    ->Args({3000, 16})
    ->Args({3000, 64})
    ->Args({5000, 16})
    ->Args({5000, 64})
    ->Unit(benchmark::kMillisecond)
    ->UseRealTime()
    ->Iterations(1); // one densified-Ã solve at the large end is multi-second

} // namespace
