// risk_covariance_bench.cpp — S8.8: the full S8 covariance-construction compute
// profile (research §10 deliverable).
//
// Two benches:
//
//   * BM_FactorCovBuild — wall-time of FactorModelBuilder::build over a
//     representative synthetic universe with the FULL S8 feature set engaged
//     (robust regression, EWMA+NW factor cov, short/long-horizon blend, seeded
//     Monte-Carlo eigenfactor de-biasing, VRA, EWMA+NW structural specific risk).
//     N ≈ 500 instruments, window ≈ 250 dates — modest so the bench finishes in
//     seconds; the PRODUCTION target is a 3,000–5,000-stock universe (research §1).
//
//   * BM_FactorCovCondition — reports the CONDITION NUMBER of F (max/min eigenvalue)
//     for the P4 single-MLE path vs the full S8 cleaned path (blend + eigen-adjust)
//     on the SAME synthetic factor-return series, as Google Benchmark counters
//     (`cond_p4`, `cond_s8`). This is the §10 compute-profile deliverable: the
//     cleaned F should be BETTER-conditioned than the raw single-window MLE.
//
// Build is Debug / clang-cl (the project default), so these are UPPER-BOUND
// latencies. Synthetic data is generated by a seeded Xoshiro256pp (bench scaffold
// only — the model path's one RNG is the seeded eigen_adjust). Mirrors the
// established cost_bench.cpp pattern (no BENCHMARK_MAIN here — it lives in
// bench_main.cpp).

#include <cmath>  // std::isnan
#include <limits> // std::numeric_limits (NaN panel sentinel, cond inf)
#include <span>
#include <vector>

#include <benchmark/benchmark.h>

#include <Eigen/Dense>

#include "atx/core/linalg/decompose.hpp" // symmetric_eig (condition number)
#include "atx/core/linalg/linalg.hpp"    // MatX, VecX
#include "atx/core/random.hpp"           // Xoshiro256pp (synthetic data)
#include "atx/core/types.hpp"            // f64, u32, u64, usize

#include "atx/engine/loop/panel_types.hpp"   // PanelView, PanelField, kPanelFieldCount
#include "atx/engine/loop/types.hpp"         // InstrumentId
#include "atx/engine/risk/cov_ewma.hpp"      // ewma_factor_covariance (S8 cleaned path)
#include "atx/engine/risk/eigen_adjust.hpp"  // eigen_adjust (S8 cleaned path)
#include "atx/engine/risk/factor_model.hpp"  // FactorModelBuilder, detail::factor_covariance
#include "atx/engine/risk/horizon_blend.hpp" // blend_factor_cov

namespace {

using atx::f64;
using atx::u32;
using atx::u64;
using atx::usize;
using atx::core::Xoshiro256pp;
using atx::core::domain::Symbol;
using atx::core::linalg::MatX;
using atx::core::linalg::VecX;
using atx::engine::InstrumentId;
using atx::engine::kPanelFieldCount;
using atx::engine::PanelField;
using atx::engine::PanelView;
using atx::engine::risk::ewma_factor_covariance;
using atx::engine::risk::FactorCovMethod;
using atx::engine::risk::FactorModelBuilder;
using atx::engine::risk::FactorModelConfig;
using atx::engine::risk::SpecificRiskMethod;

constexpr f64 kNaN = std::numeric_limits<f64>::quiet_NaN();

// ===========================================================================
//  PanelFixture — owns a PanelView's backing storage (row 0 = newest).
// ===========================================================================
class PanelFixture {
public:
  PanelFixture(usize n_rows, usize n_inst, const std::vector<std::vector<f64>> &close)
      : n_rows_{n_rows}, n_inst_{n_inst}, cap_{pow2_ceil(n_rows)},
        mask_words_{(n_inst + 63U) / 64U} {
    universe_.reserve(n_inst);
    for (usize i = 0; i < n_inst; ++i) {
      universe_.push_back(Symbol{static_cast<u32>(i + 1U)});
    }
    fields_.assign(kPanelFieldCount * cap_ * n_inst_, kNaN);
    mask_.assign(cap_ * mask_words_, 0ULL);
    for (usize r = 0; r < n_rows_; ++r) {
      const usize phys = (n_rows_ - 1U) - r;
      for (usize i = 0; i < n_inst_; ++i) {
        const f64 c = close[r][i];
        set(PanelField::Open, phys, i, c);
        set(PanelField::High, phys, i, c);
        set(PanelField::Low, phys, i, c);
        set(PanelField::Close, phys, i, c);
        set(PanelField::Volume, phys, i, 1000.0);
        if (!std::isnan(c)) {
          mask_[phys * mask_words_ + (i >> 6U)] |= (1ULL << (i & 63U));
        }
      }
    }
  }

  [[nodiscard]] PanelView view() const noexcept {
    return PanelView{fields_.data(), mask_.data(), std::span<const InstrumentId>{universe_},
                     cap_,           head_(),      n_rows_,
                     mask_words_};
  }

private:
  [[nodiscard]] usize head_() const noexcept { return (n_rows_ == 0U) ? 0U : n_rows_ - 1U; }
  static usize pow2_ceil(usize n) noexcept {
    usize p = 1U;
    while (p < n) {
      p <<= 1U;
    }
    return p;
  }
  void set(PanelField f, usize phys, usize inst_i, f64 v) noexcept {
    const usize block = static_cast<usize>(f) * cap_ * n_inst_;
    fields_[block + phys * n_inst_ + inst_i] = v;
  }
  usize n_rows_;
  usize n_inst_;
  usize cap_;
  usize mask_words_;
  std::vector<InstrumentId> universe_;
  std::vector<f64> fields_;
  std::vector<u64> mask_;
};

// Synthetic close grid: N instruments over n_rows dates (row 0 newest), driven by a
// seeded RNG so per-date returns vary across instruments. Geometric so closes stay
// positive (step_return needs close > 0).
[[nodiscard]] std::vector<std::vector<f64>> make_close(usize n_rows, usize n_inst) {
  Xoshiro256pp rng{0x5151ULL};
  std::vector<std::vector<f64>> close(n_rows, std::vector<f64>(n_inst));
  for (usize i = 0; i < n_inst; ++i) {
    f64 px = 50.0 + 0.05 * static_cast<f64>(i);
    for (usize r = n_rows; r-- > 0U;) { // oldest -> newest
      px *= 1.0 + 0.01 * rng.normal();
      close[r][i] = px;
    }
  }
  return close;
}

// Group ids: spread the universe over `n_sectors` sectors (K == n_sectors columns).
[[nodiscard]] std::vector<u32> make_groups(usize n_inst, usize n_sectors) {
  std::vector<u32> g(n_inst);
  for (usize i = 0; i < n_inst; ++i) {
    g[i] = static_cast<u32>(i % n_sectors) + 1U;
  }
  return g;
}

// The full S8 feature set (sectors-only K, no style lookback). Every build-path flag
// engaged: robust regression, EWMA+NW factor cov, short/long blend, seeded
// eigen-adjust, VRA, EWMA+NW structural specific risk.
[[nodiscard]] FactorModelConfig full_s8_cfg() {
  FactorModelConfig cfg;
  cfg.sector_factors = true;
  cfg.style_mask = 0x00; // sectors only -> no per-instrument lookback
  cfg.cov.robust_regression = true;
  cfg.cov.robust_iters = 3;
  cfg.cov.factor_cov_method = FactorCovMethod::EwmaNeweyWest;
  cfg.cov.vol_halflife = 42U;
  cfg.cov.corr_halflife = 84U;
  cfg.cov.nw_lags = 2U;
  cfg.cov.horizon_blend = true;
  cfg.cov.horizon_blend_weight = 0.5;
  cfg.cov.vol_halflife_long = 126U;
  cfg.cov.corr_halflife_long = 252U;
  cfg.cov.eigen_adjust_sims = 256U;
  cfg.cov.eigen_adjust_seed = 0xBEEFULL;
  cfg.cov.vra_halflife = 42U;
  cfg.cov.specific_method = SpecificRiskMethod::EwmaNeweyWestStructural;
  cfg.cov.spec_halflife = 42U;
  cfg.cov.spec_nw_lags = 2U;
  cfg.cov.structural_blend = true;
  cfg.cov.spec_halflife_long = 126U;
  return cfg;
}

// A synthetic T×K factor-return series (row 0 newest) with a deliberately
// ill-conditioned structure (mirrors risk_cov_ewma_test's conditioning fixture
// mechanism): the OLD half of the window (high row indices) is a near-rank-1 STALE
// regime — every factor tracks one shared driver with only a tiny idiosyncratic
// spread, so the equal-weighted single-window MLE has a tiny smallest eigenvalue
// (large condition number). The RECENT half (low row indices) is well-spread and
// independent. The EWMA split half-lives DECAY the stale collinear block out and
// anchor the correlation on the recent rows, lifting the smallest eigenvalue. Seeded;
// deterministic.
[[nodiscard]] MatX make_factor_series(usize t, usize k) {
  Xoshiro256pp rng{0x1234ULL};
  MatX f(static_cast<Eigen::Index>(t), static_cast<Eigen::Index>(k));
  const usize half = t / 2U;
  for (usize r = 0; r < t; ++r) {
    if (r < half) {
      // Recent regime: independent, comparable scale across factors (well-spread).
      for (usize c = 0; c < k; ++c) {
        f(static_cast<Eigen::Index>(r), static_cast<Eigen::Index>(c)) = 0.012 * rng.normal();
      }
    } else {
      // Stale regime: one shared driver + a tiny idiosyncratic spread ⇒ near-rank-1.
      const f64 shared = 0.012 * rng.normal();
      for (usize c = 0; c < k; ++c) {
        f(static_cast<Eigen::Index>(r), static_cast<Eigen::Index>(c)) =
            shared + 0.0004 * rng.normal();
      }
    }
  }
  return f;
}

// Condition number (max/min eigenvalue) of a symmetric PSD matrix. +inf if the
// smallest eigenvalue is non-positive or the eigensolver fails.
[[nodiscard]] f64 cond2(const MatX &a) {
  const auto eig = atx::core::linalg::symmetric_eig(a);
  if (!eig) {
    return std::numeric_limits<f64>::infinity();
  }
  const VecX &ev = eig->values; // ascending
  const f64 lo = ev[0];
  const f64 hi = ev[ev.size() - 1];
  return (lo <= 0.0) ? std::numeric_limits<f64>::infinity() : hi / lo;
}

// ---------------------------------------------------------------------------
//  Benches
// ---------------------------------------------------------------------------

// Full-S8 FactorModel build wall-time over an N-instrument, T-date universe.
void BM_FactorCovBuild(benchmark::State &state) {
  const usize n_inst = static_cast<usize>(state.range(0));
  const usize window = static_cast<usize>(state.range(1));
  const usize n_rows = window + 2U;
  const usize n_sectors = 8U; // K = 8 factors
  const std::vector<std::vector<f64>> close = make_close(n_rows, n_inst);
  const PanelFixture fx{n_rows, n_inst, close};
  const std::vector<u32> group = make_groups(n_inst, n_sectors);
  const FactorModelBuilder builder{full_s8_cfg()};
  const std::span<const f64> no_cap{};
  const std::span<const u32> grp{group};

  const std::vector<f64> probe(n_inst, 0.01);
  for (auto _ : state) {
    auto m = builder.build(fx.view(), window, no_cap, grp);
    f64 sink = m ? m->risk(std::span<const f64>{probe}) : 0.0;
    benchmark::DoNotOptimize(sink);
    benchmark::ClobberMemory();
  }
  state.SetItemsProcessed(state.iterations() * state.range(0));
}
// N ≈ 500 / window ≈ 250 (production target 3k–5k); a smaller N=200 point for scaling.
BENCHMARK(BM_FactorCovBuild)->Args({200, 250})->Args({500, 250})->Unit(benchmark::kMillisecond);

// Condition-number compute profile (research §10): the P4 single-MLE F vs the S8
// EWMA short/long-horizon BLEND vs the full S8 path (blend + seeded eigen-adjust), on
// the SAME synthetic factor-return series. Reports all three as counters.
//
//   * cond_p4    — raw single-window MLE covariance (LW intensity 0 ⇒ S itself).
//   * cond_blend — the EWMA split half-life short/long blend: this is the CONDITIONING
//                  cleaning the §10 deliverable targets (decays the stale collinear
//                  block out) and is expected BELOW cond_p4 on the ill-conditioned
//                  fixture (better-conditioned cleaned F).
//   * cond_s8    — blend + Monte-Carlo eigenfactor de-biasing (eigen_adjust). NOTE:
//                  eigen_adjust is a STATISTICAL de-biasing step (it inflates the
//                  under-forecast SMALL eigenvariances for forecast ACCURACY), not a
//                  conditioning step — it can legitimately shift cond either way. We
//                  report it so the full-path profile is honest; the conditioning
//                  improvement claim is carried by cond_blend vs cond_p4.
void BM_FactorCovCondition(benchmark::State &state) {
  const usize t = static_cast<usize>(state.range(0));
  const usize k = 8U;
  const MatX fseries = make_factor_series(t, k);

  // P4 path: the raw single-window MLE covariance (LW intensity 0 ⇒ S itself).
  const MatX f_p4 = atx::engine::risk::detail::factor_covariance(fseries, /*cfg_shrink=*/0.0);
  // S8 EWMA short/long-horizon blend (the conditioning cleaning).
  const MatX f_short = ewma_factor_covariance(fseries, /*vol_hl=*/4U, /*corr_hl=*/6U, /*L=*/0U);
  const MatX f_long = ewma_factor_covariance(fseries, /*vol_hl=*/8U, /*corr_hl=*/12U, /*L=*/0U);
  const MatX f_blend = atx::engine::risk::blend_factor_cov(f_short, f_long, 0.5);
  // Full S8 path: the blend, then seeded Monte-Carlo eigenfactor de-biasing.
  const auto adj = atx::engine::risk::eigen_adjust(f_blend, /*sims=*/256U, /*amplify=*/1.0,
                                                   /*seed=*/0xBEEFULL);
  const MatX f_s8 = adj ? *adj : f_blend;

  const f64 cond_p4 = cond2(f_p4);
  const f64 cond_blend = cond2(f_blend);
  const f64 cond_s8 = cond2(f_s8);
  for (auto _ : state) {
    f64 sink = cond_p4 + cond_blend + cond_s8; // mutable lvalue -> non-deprecated DoNotOptimize
    benchmark::DoNotOptimize(sink);
    benchmark::ClobberMemory();
  }
  state.counters["cond_p4"] = cond_p4;
  state.counters["cond_blend"] = cond_blend;
  state.counters["cond_s8"] = cond_s8;
}
BENCHMARK(BM_FactorCovCondition)->Arg(250);

} // namespace
