#pragma once

// AUTO-GENERATED by scripts/gen_kalman_ref.py — DO NOT EDIT BY HAND.
// Regenerate: python scripts/gen_kalman_ref.py > atx-engine/tests/fixtures/kalman_reg_reference.hpp
//
// Known-value reference fixture for the Chan 2-state time-varying Kalman
// regression op.  Must stay in sync with state_ops.hpp::kalman_reg_step.
//
// Inputs: x, y (T=8 dates, 1 instrument); delta=1e-4; R=1e-3.
// All values computed by the Python recursion in gen_kalman_ref.py which
// mirrors the C++ kernel exactly.

#include <limits>

namespace atx::engine::alpha::kalman_ref {

inline constexpr std::size_t kRefT = 8;

inline constexpr double kRefX[] = {1.0, 2.0, 3.0, 2.5, 4.0, 3.5, 5.0, 4.5};
inline constexpr double kRefY[] = {1.1, 2.3, 2.9, 2.6, 4.2, 3.4, 5.1, 4.6};
inline constexpr double kRefAlpha[] = {0.5497251649038064, -0.0951587638093021, 0.2590507427432535, 0.26402737779156366, 0.1765392937741488, 0.16334336292240112, 0.12549698709729187, 0.12702697492595502};
inline constexpr double kRefBeta[] = {0.5497251649038064, 1.1969334649865564, 0.9080040596437136, 0.9217760764204237, 0.9939344459087579, 0.9498107629229534, 0.9879780193618157, 0.9923115571994616};
inline constexpr double kRefResid[] = {0.7775842151343144, 0.9169280873399993, -7.033898929772263, 1.4956211231543872, 3.4462622368173474, -4.7313668017468355, 2.5482309064985014, 0.46534469548929785};

} // namespace atx::engine::alpha::kalman_ref

