from __future__ import annotations

from ._common import (
    DEFAULT_DB_PATH,
    Path,
    _month_end,
    _month_end_asof_ts,
    _normalize_ids,
    _normalize_strings,
    _normalize_symbols,
    _register_filter,
    connect,
    dt,
    end_of_day_asof_ts,
    pd,
)

from .security import (
    SECURITY_MASTER_ASOF_SQL,
    LISTING_STATUS_ASOF_SQL,
    DELISTING_EVENTS_ASOF_SQL,
    DELISTING_RETURN_OBSERVATIONS_ASOF_SQL,
    security_master_asof,
    listing_status_asof,
    delisting_events_asof,
    delisting_return_observations_asof,
)

from .fundamentals import (
    FUNDAMENTALS_ASOF_SQL,
    FUNDAMENTAL_STATEMENTS_ASOF_SQL,
    FUNDAMENTAL_TTM_ASOF_SQL,
    FUNDAMENTAL_PERIODS_ASOF_SQL,
    SHARES_OUTSTANDING_ASOF_SQL,
    fundamentals_asof,
    fundamental_statements_asof,
    fundamental_ttm_asof,
    fundamental_periods_asof,
    shares_outstanding_asof,
)

from .pricing import (
    ADJUSTMENT_FACTORS_ASOF_SQL,
    DAILY_ADJUSTMENT_FACTORS_ASOF_SQL,
    DAILY_PANEL_ASOF_SQL,
    FEATURES_ASOF_SQL,
    SHORT_INTEREST_ASOF_SQL,
    MACRO_ASOF_SQL,
    UNIVERSE_ASOF_SQL,
    UNIVERSE_MEMBERSHIP_ASOF_SQL,
    CORPORATE_ACTIONS_ASOF_SQL,
    adjustment_factors_asof,
    daily_adjustment_factors_asof,
    daily_panel_asof,
    features_asof,
    short_interest_asof,
    macro_asof,
    universe_asof,
    universe_membership_asof,
    corporate_actions_asof,
)

from .ownership import (
    THIRTEENF_POSITIONING_ASOF_SQL,
    OWNERSHIP_ASOF_SQL,
    INSIDER_TRANSACTIONS_ASOF_SQL,
    INSIDER_RELATIONSHIPS_ASOF_SQL,
    INSIDER_TRANSACTION_METRICS_ASOF_SQL,
    SECURITY_LISTING_METRICS_ASOF_SQL,
    FORM144_INTENTS_ASOF_SQL,
    FORM144_RECONCILIATION_ASOF_SQL,
    BLOCKHOLDER_ASOF_SQL,
    thirteenf_positioning_asof,
    ownership_asof,
    insider_transactions_asof,
    insider_relationships_asof,
    insider_transaction_metrics_asof,
    security_listing_metrics_asof,
    form144_intents_asof,
    form144_reconciliation_asof,
    blockholder_asof,
)

from .identifiers import (
    IDENTIFIER_DECISIONS_ASOF_SQL,
    ENTITY_CLASSIFICATION_ASOF_SQL,
    FILER_ALIASES_ASOF_SQL,
    entity_classification_asof,
    identifier_decisions_asof,
    filer_aliases_asof,
)

from .estimates import (
    ESTIMATE_SECURITY_LINKS_CTE,
    ESTIMATE_SECURITY_LINK_JOIN,
    ESTIMATE_SECURITY_LINK_ASOF_SQL,
    est_actual_asof,
    est_surprise_asof,
    est_security_links_asof,
    est_consensus_asof,
    est_guidance_asof,
    est_detail_asof,
    est_recommendation_asof,
    est_recommendation_summary_asof,
)

from .offexchange import (
    OFFEXCHANGE_VOLUME_ASOF_SQL,
    OFFEXCHANGE_SECURITY_PERIOD_ASOF_SQL,
    FINRA_SHORT_VOLUME_ASOF_SQL,
    SHORT_VOLUME_METRICS_ASOF_SQL,
    OFFEXCHANGE_QUALITY_REPORT_ASOF_SQL,
    offexchange_volume_asof,
    offexchange_security_period_asof,
    finra_short_volume_asof,
    short_volume_metrics_asof,
    offexchange_quality_report_asof,
)

from .metrics import (
    FUNDAMENTAL_XBRL_METRIC_ASOF_SQL,
    FUNDAMENTAL_RATIOS_ASOF_SQL,
    FUNDAMENTAL_RATIOS_ASOF_MONTH_SQL,
    fundamental_xbrl_metric_asof,
    fundamental_ratios_asof,
    fundamental_ratios_asof_month,
    pit_snapshot_asof,
    CORPORATE_ACTION_DIVIDEND_METRICS_ASOF_SQL,
    corporate_action_dividend_metrics_asof,
    CORPORATE_ACTION_SPLIT_METRICS_ASOF_SQL,
    corporate_action_split_metrics_asof,
    CORPORATE_ACTION_FACTOR_RECONCILIATION_ASOF_SQL,
    corporate_action_factor_reconciliation_asof,
    EQUITY_PRICE_METRICS_ASOF_SQL,
    MARKET_CAP_ASOF_SQL,
    ENTERPRISE_VALUE_ASOF_SQL,
    VALUATION_MULTIPLES_ASOF_SQL,
    market_cap_asof,
    enterprise_value_asof,
    valuation_multiples_asof,
    equity_price_metrics_asof,
    MACRO_METRICS_ASOF_SQL,
    macro_metrics_asof,
    THIRTEENF_POSITION_METRICS_ASOF_SQL,
    thirteenf_position_metrics_asof,
    THIRTEENF_OPTION_METRICS_ASOF_SQL,
    thirteenf_option_metrics_asof,
    THIRTEENF_CONCENTRATION_METRICS_ASOF_SQL,
    thirteenf_concentration_metrics_asof,
    SHORT_INTEREST_METRICS_ASOF_SQL,
    short_interest_metrics_asof,
    FORMULA_REGISTRY_ASOF_SQL,
    formula_registry_asof,
)

from .catalog import (
    WAREHOUSE_CATALOG_ASOF_SQL,
    warehouse_catalog_asof,
)

from .cli import (
    _parse_csv_arg,
    _build_arg_parser,
    main,
)

for _function_name in (
    "_month_end",
    "_month_end_asof_ts",
    "end_of_day_asof_ts",
    "_normalize_symbols",
    "_normalize_strings",
    "_normalize_ids",
    "_register_filter",
    "security_master_asof",
    "listing_status_asof",
    "delisting_events_asof",
    "delisting_return_observations_asof",
    "fundamentals_asof",
    "fundamental_statements_asof",
    "fundamental_ttm_asof",
    "fundamental_periods_asof",
    "shares_outstanding_asof",
    "adjustment_factors_asof",
    "daily_adjustment_factors_asof",
    "daily_panel_asof",
    "features_asof",
    "short_interest_asof",
    "macro_asof",
    "universe_asof",
    "universe_membership_asof",
    "corporate_actions_asof",
    "thirteenf_positioning_asof",
    "ownership_asof",
    "insider_transactions_asof",
    "insider_relationships_asof",
    "insider_transaction_metrics_asof",
    "security_listing_metrics_asof",
    "form144_intents_asof",
    "form144_reconciliation_asof",
    "blockholder_asof",
    "entity_classification_asof",
    "est_actual_asof",
    "est_surprise_asof",
    "est_security_links_asof",
    "est_consensus_asof",
    "est_guidance_asof",
    "est_detail_asof",
    "est_recommendation_asof",
    "est_recommendation_summary_asof",
    "identifier_decisions_asof",
    "filer_aliases_asof",
    "offexchange_volume_asof",
    "offexchange_security_period_asof",
    "finra_short_volume_asof",
    "short_volume_metrics_asof",
    "offexchange_quality_report_asof",
    "fundamental_xbrl_metric_asof",
    "fundamental_ratios_asof",
    "fundamental_ratios_asof_month",
    "pit_snapshot_asof",
    "corporate_action_dividend_metrics_asof",
    "corporate_action_split_metrics_asof",
    "corporate_action_factor_reconciliation_asof",
    "market_cap_asof",
    "enterprise_value_asof",
    "valuation_multiples_asof",
    "equity_price_metrics_asof",
    "macro_metrics_asof",
    "thirteenf_position_metrics_asof",
    "thirteenf_option_metrics_asof",
    "thirteenf_concentration_metrics_asof",
    "short_interest_metrics_asof",
    "formula_registry_asof",
    "warehouse_catalog_asof",
    "_parse_csv_arg",
    "_build_arg_parser",
    "main",
):
    globals()[_function_name].__module__ = __name__
del _function_name

for _module_name in (
    "_common",
    "security",
    "fundamentals",
    "pricing",
    "ownership",
    "identifiers",
    "estimates",
    "offexchange",
    "metrics",
    "catalog",
    "cli",
):
    globals().pop(_module_name, None)
del _module_name
