"""PF3-S6 migration bodies: ratio formula catalog expansion."""

from __future__ import annotations

import hashlib

import duckdb

from ._runner import Migration
from .bodies_0001_0137 import (
    _catalog_fields_for_tables,
    _formula_registry_catalog_view,
    _formula_registry_schema_catalog,
)
from .bodies_0140_0143 import _refresh_schema_contract_v2_pin


_S6_0_FORMULA_REGISTRY_ROWS = (
    (
        "pretax_margin",
        "profitability",
        "ratio",
        "ratio",
        "pretax_income",
        "revenue",
        "[1023]",
        "[1001]",
        '["pretax_income", "rev"]',
        "divide",
        "key:pretax_income|key:rev",
        "require_positive_denominator",
        "Pretax income divided by revenue.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "effective_tax_rate",
        "profitability",
        "ratio",
        "ratio",
        "income_tax",
        "pretax_income",
        "[1024]",
        "[1023]",
        '["income_tax", "pretax_income"]',
        "divide",
        "key:income_tax|key:pretax_income",
        "require_positive_denominator",
        "Income tax expense divided by pretax income.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "sga_to_revenue",
        "profitability",
        "ratio",
        "ratio",
        "selling_general_and_administrative_expense",
        "revenue",
        None,
        "[1001]",
        '["selling_general_and_administrative_expense", "rev"]',
        "divide",
        "key:selling_general_and_administrative_expense|key:rev",
        "require_positive_denominator",
        "Selling general and administrative expense divided by revenue.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "return_on_capital",
        "profitability",
        "ratio",
        "ratio",
        "operating_income",
        "long_term_debt_plus_equity",
        "[1014]",
        "[1207, 1221]",
        '["oi", "long_term_debt", "equity"]',
        "divide",
        "key:oi|sum:long_term_debt,equity",
        "require_positive_denominator",
        "Operating income divided by long-term debt plus stockholders' equity.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "inventory_turnover",
        "efficiency",
        "ratio",
        "ratio",
        "cost_of_revenue",
        "inventory",
        "[1003]",
        "[1107]",
        '["cost_of_revenue", "inventory"]',
        "divide",
        "key:cost_of_revenue|key:inventory",
        "require_positive_denominator",
        "Cost of revenue divided by inventory.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "payables_turnover",
        "efficiency",
        "ratio",
        "ratio",
        "cost_of_revenue",
        "accounts_payable",
        "[1003]",
        "[1203]",
        '["cost_of_revenue", "accounts_payable"]',
        "divide",
        "key:cost_of_revenue|key:accounts_payable",
        "require_positive_denominator",
        "Cost of revenue divided by accounts payable.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "working_capital_turnover",
        "efficiency",
        "ratio",
        "ratio",
        "revenue",
        "working_capital",
        "[1001]",
        "[1102, 1202]",
        '["rev", "current_assets", "current_liabilities"]',
        "divide",
        "key:rev|diff:current_assets,current_liabilities",
        "require_positive_denominator",
        "Revenue divided by working capital.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "long_term_debt_to_capital",
        "leverage",
        "ratio",
        "ratio",
        "long_term_debt",
        "long_term_debt_plus_equity",
        "[1207]",
        "[1207, 1221]",
        '["long_term_debt", "equity"]',
        "divide",
        "key:long_term_debt|sum:long_term_debt,equity",
        "require_positive_denominator",
        "Long-term debt divided by long-term debt plus stockholders' equity.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "net_debt_to_capital",
        "leverage",
        "ratio",
        "ratio",
        "net_debt",
        "long_term_debt_plus_equity",
        "[1207, 1104]",
        "[1207, 1221]",
        '["long_term_debt", "cash_and_equivalents", "equity"]',
        "divide",
        "diff:long_term_debt,cash_and_equivalents|sum:long_term_debt,equity",
        "require_positive_denominator",
        "Net debt divided by long-term debt plus stockholders' equity.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "long_term_debt_to_ebitda",
        "leverage",
        "ratio",
        "ratio",
        "long_term_debt",
        "ebitda",
        "[1207]",
        "[1014, 1307]",
        '["long_term_debt", "oi", "depreciation_amortization"]',
        "divide",
        "key:long_term_debt|sum:oi,depreciation_amortization",
        "require_positive_denominator",
        "Long-term debt divided by EBITDA.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "net_debt_to_ebitda",
        "leverage",
        "ratio",
        "ratio",
        "net_debt",
        "ebitda",
        "[1207, 1104]",
        "[1014, 1307]",
        '["long_term_debt", "cash_and_equivalents", "oi", "depreciation_amortization"]',
        "divide",
        "diff:long_term_debt,cash_and_equivalents|sum:oi,depreciation_amortization",
        "require_positive_denominator",
        "Net debt divided by EBITDA.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "operating_cash_flow_to_debt",
        "leverage",
        "ratio",
        "ratio",
        "operating_cash_flow",
        "long_term_debt",
        "[1301]",
        "[1207]",
        '["ocf", "long_term_debt"]',
        "divide",
        "key:ocf|key:long_term_debt",
        "require_positive_denominator",
        "Operating cash flow divided by long-term debt.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "cash_to_assets",
        "liquidity",
        "ratio",
        "ratio",
        "cash_and_equivalents",
        "assets",
        "[1104]",
        "[1101]",
        '["cash_and_equivalents", "assets"]',
        "divide",
        "key:cash_and_equivalents|key:assets",
        "require_positive_denominator",
        "Cash and equivalents divided by total assets.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "current_assets_to_assets",
        "liquidity",
        "ratio",
        "ratio",
        "current_assets",
        "assets",
        "[1102]",
        "[1101]",
        '["current_assets", "assets"]',
        "divide",
        "key:current_assets|key:assets",
        "require_positive_denominator",
        "Current assets divided by total assets.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "current_liabilities_to_assets",
        "liquidity",
        "ratio",
        "ratio",
        "current_liabilities",
        "assets",
        "[1202]",
        "[1101]",
        '["current_liabilities", "assets"]',
        "divide",
        "key:current_liabilities|key:assets",
        "require_positive_denominator",
        "Current liabilities divided by total assets.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "capex_per_share",
        "per_share",
        "per_share",
        "currency_per_share",
        "abs_capital_expenditures",
        "shares_outstanding",
        "[1305]",
        "[1039]",
        '["capex", "shares"]',
        "divide",
        "abs:capex|key:shares",
        None,
        "Absolute capital expenditures divided by shares outstanding.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "dividends_per_share",
        "per_share",
        "per_share",
        "currency_per_share",
        "abs_dividends_paid",
        "shares_outstanding",
        "[1318]",
        "[1039]",
        '["div", "shares"]',
        "divide",
        "abs:div|key:shares",
        None,
        "Absolute dividends paid divided by shares outstanding.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "cash_per_share",
        "per_share",
        "per_share",
        "currency_per_share",
        "cash_and_equivalents",
        "shares_outstanding",
        "[1104]",
        "[1039]",
        '["cash_and_equivalents", "shares"]',
        "divide",
        "key:cash_and_equivalents|key:shares",
        None,
        "Cash and equivalents divided by shares outstanding.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "price_to_cash_flow",
        "valuation",
        "ratio",
        "ratio",
        "market_cap",
        "operating_cash_flow_ttm",
        None,
        "[1301]",
        '["market_cap", "ocf"]',
        "divide",
        "key:market_cap|key:ocf",
        "require_positive_denominator",
        "Market capitalization divided by trailing-twelve-month operating cash flow.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "price_to_free_cash_flow",
        "valuation",
        "ratio",
        "ratio",
        "market_cap",
        "free_cash_flow_ttm",
        None,
        "[1301, 1305]",
        '["market_cap", "ocf", "capex"]',
        "divide",
        "key:market_cap|sum:ocf,capex",
        "require_positive_denominator",
        "Market capitalization divided by trailing-twelve-month free cash flow.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "ev_to_ebit",
        "valuation",
        "ratio",
        "ratio",
        "enterprise_value",
        "operating_income",
        None,
        "[1014]",
        '["enterprise_value", "oi"]',
        "divide",
        "key:enterprise_value|key:oi",
        "require_positive_denominator",
        "Enterprise value divided by operating income.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "ev_to_fcf",
        "valuation",
        "ratio",
        "ratio",
        "enterprise_value",
        "free_cash_flow_ttm",
        None,
        "[1301, 1305]",
        '["enterprise_value", "ocf", "capex"]',
        "divide",
        "key:enterprise_value|sum:ocf,capex",
        "require_positive_denominator",
        "Enterprise value divided by trailing-twelve-month free cash flow.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "ev_to_assets",
        "valuation",
        "ratio",
        "ratio",
        "enterprise_value",
        "assets",
        None,
        "[1101]",
        '["enterprise_value", "assets"]',
        "divide",
        "key:enterprise_value|key:assets",
        "require_positive_denominator",
        "Enterprise value divided by total assets.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "buyback_yield",
        "valuation",
        "ratio",
        "ratio",
        "abs_share_repurchases_ttm",
        "market_cap",
        "[1312]",
        None,
        '["repurch", "market_cap"]',
        "divide",
        "abs:repurch|key:market_cap",
        "require_positive_denominator",
        "Absolute trailing-twelve-month share repurchases divided by market capitalization.",
        None,
        "1900-01-01",
        None,
    ),
    (
        "shareholder_yield",
        "valuation",
        "ratio",
        "ratio",
        "abs_dividends_plus_repurchases_ttm",
        "market_cap",
        "[1312, 1318]",
        None,
        '["div", "repurch", "market_cap"]',
        "divide",
        "abs_sum:div,repurch|key:market_cap",
        "require_positive_denominator",
        "Absolute trailing-twelve-month dividends plus share repurchases divided by market capitalization.",
        None,
        "1900-01-01",
        None,
    ),
)


def _pf3_s6_ratio_formula_catalog_expansion(conn: duckdb.DuckDBPyConnection) -> None:
    """PF3-S6 S6-0: persist the expanded ratio formula catalog."""

    _formula_registry_schema_catalog(conn)
    rows_sha256 = hashlib.sha256(
        repr(_S6_0_FORMULA_REGISTRY_ROWS).encode("utf-8")
    ).hexdigest()
    expected_rows_sha256 = (
        "e6fce500fc27ccd2beaac2250b945b9e6832844f8830d09b40f60ac054ac0477"
    )
    if rows_sha256 != expected_rows_sha256:
        raise RuntimeError("PF3-S6 S6-0 formula_registry row payload hash mismatch")

    conn.execute(
        """
        CREATE TEMP TABLE IF NOT EXISTS _pf3_s6_formula_registry_seed_rows (
            formula_code VARCHAR PRIMARY KEY,
            family VARCHAR NOT NULL,
            kind VARCHAR NOT NULL,
            unit VARCHAR NOT NULL,
            numerator_code VARCHAR,
            denominator_code VARCHAR,
            numerator_item_ids_json VARCHAR,
            denominator_item_ids_json VARCHAR,
            inputs_json VARCHAR NOT NULL,
            transform VARCHAR NOT NULL,
            expression VARCHAR,
            is_meaningful_rule VARCHAR,
            definition VARCHAR NOT NULL,
            citation VARCHAR,
            valid_from DATE NOT NULL,
            valid_to DATE
        )
        """
    )
    conn.execute("DELETE FROM _pf3_s6_formula_registry_seed_rows")
    conn.executemany(
        """
        INSERT INTO _pf3_s6_formula_registry_seed_rows (
            formula_code,
            family,
            kind,
            unit,
            numerator_code,
            denominator_code,
            numerator_item_ids_json,
            denominator_item_ids_json,
            inputs_json,
            transform,
            expression,
            is_meaningful_rule,
            definition,
            citation,
            valid_from,
            valid_to
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS DATE), CAST(? AS DATE))
        """,
        _S6_0_FORMULA_REGISTRY_ROWS,
    )
    conn.execute(
        """
        UPDATE formula_registry AS target
        SET family = seed.family,
            kind = seed.kind,
            unit = seed.unit,
            numerator_code = seed.numerator_code,
            denominator_code = seed.denominator_code,
            numerator_item_ids_json = seed.numerator_item_ids_json,
            denominator_item_ids_json = seed.denominator_item_ids_json,
            inputs_json = seed.inputs_json,
            transform = seed.transform,
            expression = seed.expression,
            is_meaningful_rule = seed.is_meaningful_rule,
            definition = seed.definition,
            citation = seed.citation,
            valid_from = seed.valid_from,
            valid_to = seed.valid_to,
            run_id = NULL,
            source_loaded_at = now()
        FROM _pf3_s6_formula_registry_seed_rows AS seed
        WHERE target.formula_code = seed.formula_code
        """
    )
    conn.execute(
        """
        INSERT INTO formula_registry (
            formula_code,
            family,
            kind,
            unit,
            numerator_code,
            denominator_code,
            numerator_item_ids_json,
            denominator_item_ids_json,
            inputs_json,
            transform,
            expression,
            is_meaningful_rule,
            definition,
            citation,
            valid_from,
            valid_to
        )
        SELECT seed.formula_code,
               seed.family,
               seed.kind,
               seed.unit,
               seed.numerator_code,
               seed.denominator_code,
               seed.numerator_item_ids_json,
               seed.denominator_item_ids_json,
               seed.inputs_json,
               seed.transform,
               seed.expression,
               seed.is_meaningful_rule,
               seed.definition,
               seed.citation,
               seed.valid_from,
               seed.valid_to
        FROM _pf3_s6_formula_registry_seed_rows AS seed
        WHERE NOT EXISTS (
            SELECT 1
            FROM formula_registry AS target
            WHERE target.formula_code = seed.formula_code
        )
        """
    )
    conn.execute("DROP TABLE IF EXISTS _pf3_s6_formula_registry_seed_rows")
    _formula_registry_catalog_view(conn)
    _catalog_fields_for_tables(conn, ("formula_registry", "v_formula_registry"))
    _refresh_schema_contract_v2_pin(conn)


MIGRATIONS: list[Migration] = [
    Migration(
        version=148,
        name="pf3_s6_ratio_formula_catalog_expansion",
        up=_pf3_s6_ratio_formula_catalog_expansion,
    ),
]
