"""Reference fixture generator for combine_cov_targets_test.cpp (Lane 5).

Independent numpy port of Ledoit & Wolf's published Matlab code:
  * analytical_shrinkage.m  (LW 2020, Annals of Statistics 48(5); k=1 demean, n=T-1)
  * covCor.m                (LW 2003 "Honey, I shrunk..." constant-correlation target)
Inputs are generated by an exact-integer LCG mirrored in the C++ test, so only the
outputs are embedded. Run:  python gen_cov_targets_fixture.py > cov_targets_fixture.inc
"""
import numpy as np

MASK = (1 << 64) - 1


def lcg_matrix(seed, t, n):
    s = seed
    out = np.empty((t, n))
    for r in range(t):
        for c in range(n):
            s = (s * 6364136223846793005 + 1442695040888963407) & MASK
            u = ((s >> 11) / float(1 << 53)) * 2.0 - 1.0  # uniform(-1,1)
            out[r, c] = u * (1.0 + 0.25 * c)  # heteroscedastic columns
    # a common factor so the spectrum is not flat
    f = out[:, 0].copy()
    for c in range(1, n):
        out[:, c] += 0.5 * f
    return out


def lw2020(x):
    t, p = x.shape
    x = x - x.mean(axis=0)
    n = t - 1
    sample = (x.T @ x) / n
    lam, u = np.linalg.eigh(sample)
    idx = np.argsort(lam)
    lam, u = lam[idx], u[:, idx]
    lam = lam[max(0, p - n):p]
    m = min(p, n)
    L = np.tile(lam[:, None], (1, m))
    h = n ** (-1.0 / 3.0)
    H = h * L.T
    xx = (L - L.T) / H
    ftilde = (3.0 / 4.0 / np.sqrt(5.0)) * np.mean(np.maximum(1.0 - xx ** 2 / 5.0, 0.0) / H, axis=1)
    with np.errstate(divide="ignore", invalid="ignore"):
        hf = (-3.0 / 10.0 / np.pi) * xx + (3.0 / 4.0 / np.sqrt(5.0) / np.pi) * (1.0 - xx ** 2 / 5.0) * np.log(
            np.abs((np.sqrt(5.0) - xx) / (np.sqrt(5.0) + xx)))
    edge = np.abs(xx) == np.sqrt(5.0)
    hf[edge] = (-3.0 / 10.0 / np.pi) * xx[edge]
    hftilde = np.mean(hf / H, axis=1)
    if p <= n:
        c = p / n
        d = lam / ((np.pi * c * lam * ftilde) ** 2 + (1.0 - c - np.pi * c * lam * hftilde) ** 2)
    else:
        hf0 = (1.0 / np.pi) * (3.0 / 10.0 / h ** 2 + 3.0 / 4.0 / np.sqrt(5.0) / h * (1.0 - 1.0 / 5.0 / h ** 2)
                               * np.log((1.0 + np.sqrt(5.0) * h) / (1.0 - np.sqrt(5.0) * h))) * np.mean(1.0 / lam)
        d0 = 1.0 / (np.pi * (p - n) / n * hf0)
        d1 = lam / (np.pi ** 2 * lam ** 2 * (ftilde ** 2 + hftilde ** 2))
        d = np.concatenate([np.full(p - n, d0), d1])
    return u @ np.diag(d) @ u.T


def lw2003_const_corr(x):
    t, n = x.shape
    x = x - x.mean(axis=0)
    s = (x.T @ x) / t
    var = np.diag(s)
    sd = np.sqrt(var)
    r = s / np.outer(sd, sd)
    rbar = (r.sum() - n) / (n * (n - 1))
    f = rbar * np.outer(sd, sd)
    np.fill_diagonal(f, var)
    y = x ** 2
    phi_mat = (y.T @ y) / t - s ** 2
    phi = phi_mat.sum()
    theta = ((x ** 3).T @ x) / t - var[:, None] * s
    np.fill_diagonal(theta, 0.0)
    rho = np.diag(phi_mat).sum() + rbar * ((1.0 / sd)[:, None] * sd[None, :] * theta).sum()
    gamma = np.linalg.norm(s - f, "fro") ** 2
    kappa = (phi - rho) / gamma
    delta = max(0.0, min(1.0, kappa / t))
    return delta * f + (1.0 - delta) * s, delta


def emit(name, m):
    flat = m.reshape(-1)  # row-major
    print(f"// {name}: {m.shape[0]}x{m.shape[1]} row-major")
    print(f"inline constexpr double {name}[] = {{")
    for i in range(0, flat.size, 4):
        print("    " + ", ".join(f"{v:.17g}" for v in flat[i:i + 4]) + ",")
    print("};")


if __name__ == "__main__":
    print("// GENERATED by gen_cov_targets_fixture.py -- do not edit by hand.")
    xa = lcg_matrix(12345, 60, 8)    # c = 8/59 < 1
    xb = lcg_matrix(777, 24, 30)     # c = 30/23 > 1 (null-space variant)
    emit("kLw2020A", lw2020(xa))
    emit("kLw2020B", lw2020(xb))
    cc, dcc = lw2003_const_corr(xa)
    emit("kLw2003CcA", cc)
    print(f"inline constexpr double kLw2003CcADelta = {dcc:.17g};")
