"""Type stubs for the compiled atxpy._core extension."""

class AtxError(Exception): ...

class Decimal:
    @staticmethod
    def from_raw(mantissa: int) -> Decimal: ...
    @staticmethod
    def from_int(whole: int) -> Decimal: ...
    @staticmethod
    def from_double(value: float) -> Decimal: ...
    @staticmethod
    def from_string(text: str) -> Decimal: ...
    def raw(self) -> int: ...
    def to_double(self) -> float: ...
    def to_string(self) -> str: ...
    def round(self) -> Decimal: ...
    def __add__(self, other: Decimal) -> Decimal: ...
    def __sub__(self, other: Decimal) -> Decimal: ...
    def __mul__(self, other: Decimal) -> Decimal: ...
    def __truediv__(self, other: Decimal) -> Decimal: ...
    def __neg__(self) -> Decimal: ...
    def __float__(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Decimal) -> bool: ...
    def __le__(self, other: Decimal) -> bool: ...
    def __gt__(self, other: Decimal) -> bool: ...
    def __ge__(self, other: Decimal) -> bool: ...
    def __hash__(self) -> int: ...

class Symbol:
    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Symbol) -> bool: ...
    def __hash__(self) -> int: ...

class SymbolTable:
    def __init__(self) -> None: ...
    def intern(self, name: str) -> Symbol: ...
    def name(self, symbol: Symbol) -> str: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...

import enum
from typing import Tuple

import numpy as np

class Transform(enum.Enum):
    Rank = ...
    ZScore = ...

class SlippageMode(enum.Enum):
    VolumeShare = ...
    FixedBps = ...

class CommissionMode(enum.Enum):
    PerShare = ...
    PerDollar = ...

class OrderType(enum.Enum):
    Market = ...
    Limit = ...

class FillCfg:
    allow_same_bar_fill: bool
    def __init__(self) -> None: ...

class SlippageCfg:
    mode: SlippageMode
    k: float
    bps: float
    cap_volshare: float
    cap_bps: float
    def __init__(self) -> None: ...

class ImpactCfg:
    Y: float
    delta: float
    gamma: float
    def __init__(self) -> None: ...

class CommissionCfg:
    mode: CommissionMode
    per_share: float
    min_fee: float
    max_pct: float
    per_dollar_bps: float
    def __init__(self) -> None: ...

class LatencyCfg:
    latency_nanos: int
    def __init__(self) -> None: ...

class VolumeCapCfg:
    volume_limit: float
    def __init__(self) -> None: ...

class InstrumentStats:
    adv: float
    sigma: float
    spread: float
    def __init__(self) -> None: ...

class WeightPolicy:
    transform: Transform
    industry_neutral: bool
    dollar_neutral: bool
    gross_leverage: float
    truncation: float
    winsorize_limit: float
    def __init__(self) -> None: ...

class BarsForSymbol:
    ts_nanos: list[int]
    open: list[float]
    high: list[float]
    low: list[float]
    close: list[float]
    volume: list[float]
    def __init__(self) -> None: ...

class Library:
    def __init__(self) -> None: ...
    def size(self) -> int: ...

class Ast: ...

class Analysis:
    @property
    def required_lookback(self) -> int: ...

class Program:
    @property
    def required_lookback(self) -> int: ...
    @property
    def num_slots(self) -> int: ...
    @property
    def fields(self) -> list[str]: ...
    @property
    def roots(self) -> list[str]: ...
    def cache_hit_pct(self) -> float: ...

def parse_expr(source: str, library: Library) -> Ast: ...
def analyze(ast: Ast) -> Analysis: ...
def compile(ast: Ast, analysis: Analysis) -> Program: ...
def compile_alpha(source: str) -> Program: ...
def evaluate_program(program: Program, fields: dict[str, np.ndarray]) -> np.ndarray: ...

class BacktestParams:
    symbols: list[str]
    bars: list[BarsForSymbol]
    starting_cash: str
    signals: list[list[float]]
    alpha_expr: str
    max_lookback: int
    every: int
    delay_same: bool
    policy: WeightPolicy
    fill: FillCfg
    slip: SlippageCfg
    impact: ImpactCfg
    comm: CommissionCfg
    latency: LatencyCfg
    volcap: VolumeCapCfg
    stats: list[InstrumentStats]
    def __init__(self) -> None: ...

class BacktestResult:
    @property
    def slices(self) -> int: ...
    @property
    def rebalances(self) -> int: ...
    @property
    def turnover(self) -> float: ...
    @property
    def final_equity(self) -> float: ...
    @property
    def final_cash(self) -> Decimal: ...
    def equity_columns(
        self,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
    def fills_columns(
        self,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

def run_backtest(params: BacktestParams) -> BacktestResult: ...

# ---- eval ----
from typing import Optional

class ReturnMetrics:
    @property
    def sharpe(self) -> float: ...
    @property
    def sortino(self) -> float: ...
    @property
    def max_dd(self) -> float: ...
    @property
    def calmar(self) -> float: ...
    @property
    def ir(self) -> float: ...
    @property
    def appraisal(self) -> float: ...
    @property
    def hit_rate(self) -> float: ...

class DsrResult:
    @property
    def psr(self) -> float: ...
    @property
    def sr_star(self) -> float: ...
    @property
    def dsr(self) -> float: ...
    @property
    def haircut_sharpe(self) -> float: ...

class PboResult:
    @property
    def pbo(self) -> float: ...
    @property
    def split_logits(self) -> list[float]: ...
    @property
    def mean_logit(self) -> float: ...

class MeanStd:
    @property
    def mean(self) -> float: ...
    @property
    def std(self) -> float: ...

class LabelSpan:
    t0: int
    t1: int
    def __init__(self, t0: int, t1: int) -> None: ...

class CpcvConfig:
    n_groups: int
    n_test_groups: int
    embargo: float
    def __init__(self) -> None: ...

class CpcvFold:
    @property
    def train_idx(self) -> list[int]: ...
    @property
    def test_idx(self) -> list[int]: ...

def compute_return_metrics(pnl: list[float], periods_per_year: float = ...) -> ReturnMetrics: ...
def deflated_sharpe(sr: float, n_obs: int, skew: float = ..., excess_kurtosis: float = ...,
                    n_trials: int = ..., variance: Optional[float] = ...) -> DsrResult: ...
def pbo_cscv(perf: list[float], n_candidates: int, n_splits: int) -> PboResult: ...
def cpcv_folds(spans: list[LabelSpan], config: CpcvConfig) -> list[CpcvFold]: ...
def mean_std_pop(series: list[float]) -> MeanStd: ...
def skewness(series: list[float]) -> float: ...
def excess_kurtosis(series: list[float]) -> float: ...
def median(series: list[float]) -> float: ...
def norm_cdf(x: float) -> float: ...
def norm_ppf(p: float) -> float: ...
def returns_from_equity(equity: list[float]) -> list[float]: ...

# ---- risk ----
class FactorModel:
    @property
    def n_factors(self) -> int: ...
    @property
    def n_instruments(self) -> int: ...
    def risk(self, weights: list[float]) -> float: ...
    def neutralize(self, signal: list[float]) -> list[float]: ...

def make_factor_model(X: np.ndarray, F: np.ndarray, D: np.ndarray,
                      fit_begin: int = ..., fit_end: int = ...) -> FactorModel: ...

class OptimizerConfig:
    risk_aversion: float
    turnover_penalty: float
    gross_leverage: float
    name_cap: float
    dollar_neutral: bool
    max_iters: int
    def __init__(self) -> None: ...

class PortfolioOptimizer:
    cfg: OptimizerConfig
    def __init__(self, config: OptimizerConfig) -> None: ...
    def solve(self, alpha: list[float], model: FactorModel,
              w_prev: list[float] = ...) -> list[float]: ...
