"""Type stubs for the compiled atxpy._core extension."""

class AtxError(Exception): ...

class Decimal:
    @staticmethod
    def from_raw(mantissa: int) -> Decimal: ...
    @staticmethod
    def from_int(whole: int) -> Decimal: ...
    @staticmethod
    def from_double(value: float) -> Decimal: ...
    @staticmethod
    def from_string(text: str) -> Decimal: ...
    def raw(self) -> int: ...
    def to_double(self) -> float: ...
    def to_string(self) -> str: ...
    def round(self) -> Decimal: ...
    def __add__(self, other: Decimal) -> Decimal: ...
    def __sub__(self, other: Decimal) -> Decimal: ...
    def __mul__(self, other: Decimal) -> Decimal: ...
    def __truediv__(self, other: Decimal) -> Decimal: ...
    def __neg__(self) -> Decimal: ...
    def __float__(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Decimal) -> bool: ...
    def __le__(self, other: Decimal) -> bool: ...
    def __gt__(self, other: Decimal) -> bool: ...
    def __ge__(self, other: Decimal) -> bool: ...
    def __hash__(self) -> int: ...

class Symbol:
    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Symbol) -> bool: ...
    def __hash__(self) -> int: ...

class SymbolTable:
    def __init__(self) -> None: ...
    def intern(self, name: str) -> Symbol: ...
    def name(self, symbol: Symbol) -> str: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
