"""
gen_kalman_ref.py — Generate a C++ known-value fixture for the Chan 2-state
time-varying Kalman regression op (kalman(y, x, delta, R)).

MUST stay in sync with atx-engine/include/atx/engine/alpha/state_ops.hpp
::atx::engine::alpha::detail::kalman_reg_step — specifically:

  Diffuse prior: a=0, b=0, P=[[1,0],[0,1]].
  W = (delta/(1-delta)) * I2.
  Per finite (y, x) observation:
    P_00 = P00 + w;  P_01 = P01;  P_11 = P11 + w    # predict P- = P + W
    yhat  = a + b*x
    e     = y - yhat
    pf0   = P_00 + P_01*x                            # (P- F^T)[0]
    pf1   = P_01 + P_11*x                            # (P- F^T)[1]
    Q_inn = pf0 + x*pf1 + R                          # innovation variance
    k0    = pf0 / Q_inn;  k1 = pf1 / Q_inn
    a    += k0*e;  b += k1*e
    P00   = P_00 - k0*pf0
    P01   = P_01 - k0*pf1
    P11   = P_11 - k1*pf1
    outputs: alpha=a, beta=b, resid=e/sqrt(Q_inn)
  NaN obs (y or x NaN): predict-only (P00+=w, P11+=w; a,b unchanged);
    outputs NaN, NaN, NaN.

Usage:
    python scripts/gen_kalman_ref.py > atx-engine/tests/fixtures/kalman_reg_reference.hpp
"""

import math
import sys

# ---------------------------------------------------------------------------
# FIXED deterministic inputs — 1 instrument, T=8 dates.
# No randomness; hardcoded floats so the fixture is reproducible.
# Mild linear trend with noise, producing non-trivial alpha/beta evolution.
# ---------------------------------------------------------------------------
x = [1.0, 2.0, 3.0, 2.5, 4.0, 3.5, 5.0, 4.5]
y = [1.1, 2.3, 2.9, 2.6, 4.2, 3.4, 5.1, 4.6]
delta = 1e-4
R = 1e-3

T = len(x)
assert len(y) == T

# ---------------------------------------------------------------------------
# Run the Chan recursion — mirrors kalman_reg_step in state_ops.hpp exactly.
# ---------------------------------------------------------------------------
a = 0.0
b = 0.0
P00 = 1.0
P01 = 0.0
P11 = 1.0

w = delta / (1.0 - delta)   # W = w * I2

ref_alpha = []
ref_beta  = []
ref_resid = []

for t in range(T):
    yt = y[t]
    xt = x[t]

    if math.isnan(yt) or math.isnan(xt):
        # predict-only
        P00 += w
        P11 += w
        ref_alpha.append(float("nan"))
        ref_beta.append(float("nan"))
        ref_resid.append(float("nan"))
        continue

    # predict
    P_00 = P00 + w
    P_01 = P01
    P_11 = P11 + w

    yhat = a + b * xt
    e    = yt - yhat

    pf0   = P_00 + P_01 * xt
    pf1   = P_01 + P_11 * xt
    Q_inn = pf0 + xt * pf1 + R

    k0 = pf0 / Q_inn
    k1 = pf1 / Q_inn

    a   += k0 * e
    b   += k1 * e
    P00  = P_00 - k0 * pf0
    P01  = P_01 - k0 * pf1
    P11  = P_11 - k1 * pf1

    ref_alpha.append(a)
    ref_beta.append(b)
    ref_resid.append(e / math.sqrt(Q_inn))

# ---------------------------------------------------------------------------
# Emit the C++ header.  Full-precision doubles (repr / %.17g so literals are
# round-trip exact).
# ---------------------------------------------------------------------------
def fmt(v):
    if math.isnan(v):
        return "std::numeric_limits<double>::quiet_NaN()"
    return repr(v)   # Python repr of float gives enough digits for round-trip

def arr(name, vals):
    body = ", ".join(fmt(v) for v in vals)
    return f"inline constexpr double {name}[] = {{{body}}};"

lines = [
    "#pragma once",
    "",
    "// AUTO-GENERATED by scripts/gen_kalman_ref.py — DO NOT EDIT BY HAND.",
    "// Regenerate: python scripts/gen_kalman_ref.py > atx-engine/tests/fixtures/kalman_reg_reference.hpp",
    "//",
    "// Known-value reference fixture for the Chan 2-state time-varying Kalman",
    "// regression op.  Must stay in sync with state_ops.hpp::kalman_reg_step.",
    "//",
    "// Inputs: x, y (T=8 dates, 1 instrument); delta=1e-4; R=1e-3.",
    "// All values computed by the Python recursion in gen_kalman_ref.py which",
    "// mirrors the C++ kernel exactly.",
    "",
    "#include <limits>",
    "",
    "namespace atx::engine::alpha::kalman_ref {",
    "",
    f"inline constexpr std::size_t kRefT = {T};",
    "",
    arr("kRefX", x),
    arr("kRefY", y),
    arr("kRefAlpha", ref_alpha),
    arr("kRefBeta",  ref_beta),
    arr("kRefResid", ref_resid),
    "",
    "} // namespace atx::engine::alpha::kalman_ref",
    "",
]

print("\n".join(lines))

# ---------------------------------------------------------------------------
# Sanity-print to stderr for developer inspection during generation.
# ---------------------------------------------------------------------------
print("// Sanity check (stderr):", file=sys.stderr)
for t in range(T):
    print(f"//   t={t}: x={x[t]} y={y[t]}  "
          f"alpha={ref_alpha[t]:.15g}  beta={ref_beta[t]:.15g}  resid={ref_resid[t]:.15g}",
          file=sys.stderr)
