"""Column contracts and alias maps for estimate datasets."""
from __future__ import annotations

import json
import re
from typing import Any

_MEASURE_ROWS: list[dict[str, Any]] = [
    {
        "measure_code": "EPS_DILUTED",
        "label": "Diluted EPS",
        "statement": "income",
        "unit_type": "per_share",
        "is_per_share": True,
        "higher_is_better": True,
        "us_gaap_concepts": json.dumps(["EarningsPerShareDiluted"]),
        "source": "est_measure_seed",
    },
    {
        "measure_code": "EPS_BASIC",
        "label": "Basic EPS",
        "statement": "income",
        "unit_type": "per_share",
        "is_per_share": True,
        "higher_is_better": True,
        "us_gaap_concepts": json.dumps(["EarningsPerShareBasic"]),
        "source": "est_measure_seed",
    },
    {
        "measure_code": "REVENUE",
        "label": "Revenue",
        "statement": "income",
        "unit_type": "currency",
        "is_per_share": False,
        "higher_is_better": True,
        "us_gaap_concepts": json.dumps(
            ["Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax"]
        ),
        "source": "est_measure_seed",
    },
    {
        "measure_code": "NET_INCOME",
        "label": "Net income",
        "statement": "income",
        "unit_type": "currency",
        "is_per_share": False,
        "higher_is_better": True,
        "us_gaap_concepts": json.dumps(["NetIncomeLoss"]),
        "source": "est_measure_seed",
    },
    {
        "measure_code": "OPERATING_INCOME",
        "label": "Operating income",
        "statement": "income",
        "unit_type": "currency",
        "is_per_share": False,
        "higher_is_better": True,
        "us_gaap_concepts": json.dumps(["OperatingIncomeLoss"]),
        "source": "est_measure_seed",
    },
]

ESTIMATE_DETAIL_COLUMNS = [
    "est_detail_id",
    "security_id",
    "symbol",
    "vendor_security_id",
    "vendor_security_id_type",
    "measure_code",
    "fiscal_year",
    "fiscal_period",
    "period_end",
    "broker_id",
    "analyst_id",
    "value",
    "estimate_date",
    "as_of_date",
    "available_at",
    "provider",
    "source_vendor_table",
    "vendor_broker_id",
    "vendor_analyst_id",
    "broker_mask_code",
    "analyst_mask_code",
    "broker_name",
    "analyst_name",
    "fpi",
    "period_type",
    "expected_report_date",
    "announce_date",
    "announce_time",
    "activation_date",
    "activation_time",
    "revision_date",
    "revision_time",
    "stop_date",
    "pdf",
    "basis",
    "is_gaap",
    "estimate_type",
    "currency",
    "unit",
    "source_file",
    "source_file_sha256",
    "raw_payload_json",
    "run_id",
    "source",
]

ESTIMATE_BROKER_COLUMNS = [
    "broker_id",
    "broker_name",
    "source",
    "provider",
    "vendor_broker_id",
    "broker_mask_code",
    "valid_from",
    "valid_to",
    "available_at",
    "run_id",
    "source_file_sha256",
]

ESTIMATE_ANALYST_COLUMNS = [
    "analyst_id",
    "analyst_name",
    "broker_id",
    "source",
    "provider",
    "vendor_analyst_id",
    "analyst_mask_code",
    "valid_from",
    "valid_to",
    "available_at",
    "run_id",
    "source_file_sha256",
]

ESTIMATE_PERIOD_COLUMNS = [
    "est_period_id",
    "provider",
    "measure_code",
    "fiscal_year",
    "fiscal_period",
    "period_end",
    "fpi",
    "period_type",
    "expected_report_date",
    "valid_from",
    "valid_to",
    "as_of_date",
    "available_at",
    "source",
    "run_id",
]

ESTIMATE_BROKER_ALIAS_COLUMNS = [
    "broker_alias_id",
    "broker_id",
    "provider",
    "alias_type",
    "alias_value",
    "valid_from",
    "valid_to",
    "available_at",
    "source",
    "run_id",
]

ESTIMATE_ANALYST_ALIAS_COLUMNS = [
    "analyst_alias_id",
    "analyst_id",
    "provider",
    "alias_type",
    "alias_value",
    "valid_from",
    "valid_to",
    "available_at",
    "source",
    "run_id",
]

ESTIMATE_CONSENSUS_COLUMNS = [
    "est_consensus_id",
    "security_id",
    "symbol",
    "vendor_security_id",
    "vendor_security_id_type",
    "provider",
    "source_vendor_table",
    "measure_code",
    "fiscal_year",
    "fiscal_period",
    "period_end",
    "fpi",
    "period_type",
    "expected_report_date",
    "consensus_date",
    "mean",
    "median",
    "high",
    "low",
    "stdev",
    "num_estimates",
    "num_up",
    "num_down",
    "currency",
    "pdf",
    "basis",
    "is_gaap",
    "unit",
    "stale_after_date",
    "as_of_date",
    "available_at",
    "source_file",
    "source_file_sha256",
    "raw_payload_json",
    "run_id",
    "source",
]

ESTIMATE_GUIDANCE_COLUMNS = [
    "est_guidance_id",
    "security_id",
    "measure_code",
    "fiscal_year",
    "fiscal_period",
    "period_end",
    "low",
    "high",
    "mid",
    "guidance_type",
    "basis",
    "currency",
    "unit",
    "units_scale",
    "source_item",
    "guidance_date",
    "form",
    "accession_number",
    "as_of_date",
    "available_at",
    "extraction_confidence",
    "evidence_text",
    "source_file",
    "source_file_sha256",
    "raw_payload_json",
    "run_id",
    "source",
]

ESTIMATE_RECOMMENDATION_COLUMNS = [
    "est_recommendation_id",
    "security_id",
    "symbol",
    "vendor_security_id",
    "vendor_security_id_type",
    "cusip",
    "provider",
    "source_vendor_table",
    "broker_id",
    "analyst_id",
    "vendor_broker_id",
    "vendor_analyst_id",
    "broker_mask_code",
    "analyst_mask_code",
    "broker_name",
    "analyst_name",
    "rating",
    "rating_standardized",
    "recommendation_code",
    "recommendation_label",
    "prior_rating",
    "prior_recommendation_code",
    "prior_recommendation_label",
    "rating_scale",
    "action",
    "event_type",
    "price_target",
    "target_currency",
    "target_horizon_months",
    "industry_code",
    "is_industry_recommendation",
    "usfirm",
    "rating_date",
    "announce_date",
    "announce_time",
    "activation_date",
    "activation_time",
    "revision_date",
    "revision_time",
    "stop_date",
    "as_of_date",
    "available_at",
    "source_file",
    "source_file_sha256",
    "raw_payload_json",
    "run_id",
    "source",
]

ESTIMATE_RECOMMENDATION_SUMMARY_COLUMNS = [
    "est_recommendation_summary_id",
    "security_id",
    "symbol",
    "vendor_security_id",
    "vendor_security_id_type",
    "cusip",
    "provider",
    "source_vendor_table",
    "snapshot_date",
    "as_of_date",
    "available_at",
    "mean_recommendation",
    "median_recommendation",
    "rating_scale",
    "scale_direction",
    "strong_buy_count",
    "buy_count",
    "hold_count",
    "underperform_count",
    "sell_count",
    "buy_equivalent_count",
    "sell_equivalent_count",
    "total_recommendations",
    "mean_price_target",
    "median_price_target",
    "high_price_target",
    "low_price_target",
    "price_target_count",
    "target_currency",
    "target_horizon_months",
    "provider_scale_notes",
    "source_file",
    "source_file_sha256",
    "raw_payload_json",
    "run_id",
    "source",
]

DETAIL_COLUMN_ALIASES = {
    "actdats": "activation_date",
    "acttims": "activation_time",
    "actual_activation_date": "activation_date",
    "amaskcd": "analyst_mask_code",
    "analys": "vendor_analyst_id",
    "analyst": "analyst_name",
    "analyst_code": "vendor_analyst_id",
    "analystid": "analyst_id",
    "anntims": "announce_time",
    "anndats": "announce_date",
    "broker": "broker_name",
    "broker_code": "vendor_broker_id",
    "brokerid": "broker_id",
    "curr": "currency",
    "emaskcd": "broker_mask_code",
    "estimate": "value",
    "estimator": "vendor_broker_id",
    "est_value": "value",
    "fpedats": "period_end",
    "fiscal_period_end": "period_end",
    "ibes_ticker": "vendor_security_id",
    "measure": "measure_code",
    "oftic": "symbol",
    "official_ticker": "symbol",
    "pends": "period_end",
    "period_end_date": "period_end",
    "revdats": "revision_date",
    "revtims": "revision_time",
    "source_table": "source_vendor_table",
    "stop": "stop_date",
    "stopdate": "stop_date",
    "ticker": "vendor_security_id",
    "tic": "symbol",
    "value": "value",
}

CONSENSUS_COLUMN_ALIASES = {
    "asof": "as_of_date",
    "availabledate": "available_date",
    "available_date": "available_date",
    "availability_date": "available_date",
    "availabilitydate": "available_date",
    "availability_time": "available_time",
    "availabilitytime": "available_time",
    "currency_code": "currency",
    "curr": "currency",
    "estcur": "currency",
    "fiscal_period_end": "period_end",
    "fpedats": "period_end",
    "highest": "high",
    "high_est": "high",
    "ibes_ticker": "vendor_security_id",
    "low_est": "low",
    "lowest": "low",
    "mean_est": "mean",
    "meanest": "mean",
    "measure": "measure_code",
    "medest": "median",
    "median_est": "median",
    "num_down": "num_down",
    "num_down_30d": "num_down",
    "num_down_revisions_30d": "num_down",
    "num_est": "num_estimates",
    "num_up": "num_up",
    "num_up_30d": "num_up",
    "num_up_revisions_30d": "num_up",
    "numdown": "num_down",
    "numest": "num_estimates",
    "numup": "num_up",
    "oftic": "symbol",
    "official_ticker": "symbol",
    "pends": "period_end",
    "period_end_date": "period_end",
    "snapshot_date": "consensus_date",
    "source_table": "source_vendor_table",
    "statpers": "consensus_date",
    "stdev_est": "stdev",
    "stddev": "stdev",
    "ticker": "vendor_security_id",
    "tic": "symbol",
}

RECOMMENDATION_COLUMN_ALIASES = {
    "actdats": "activation_date",
    "acttims": "activation_time",
    "actual_activation_date": "activation_date",
    "amaskcd": "analyst_mask_code",
    "analys": "vendor_analyst_id",
    "analyst": "analyst_name",
    "analyst_code": "vendor_analyst_id",
    "analystid": "analyst_id",
    "anntims": "announce_time",
    "anndats": "announce_date",
    "asof": "as_of_date",
    "broker": "broker_name",
    "broker_code": "vendor_broker_id",
    "brokerid": "broker_id",
    "curr": "target_currency",
    "emaskcd": "broker_mask_code",
    "estcur": "target_currency",
    "estimator": "vendor_broker_id",
    "horizon": "target_horizon_months",
    "ibes_ticker": "vendor_security_id",
    "ind_idx": "industry_code",
    "industry": "industry_code",
    "ireccd": "recommendation_code",
    "itext": "rating",
    "oftic": "symbol",
    "official_ticker": "symbol",
    "prior_ireccd": "prior_recommendation_code",
    "prior_rating_code": "prior_recommendation_code",
    "ptg": "price_target",
    "rating_code": "recommendation_code",
    "recd": "recommendation_code",
    "recommendation": "recommendation_code",
    "recommendation_text": "rating",
    "rec_code": "recommendation_code",
    "revdats": "revision_date",
    "revtims": "revision_time",
    "source_table": "source_vendor_table",
    "stop": "stop_date",
    "stopdate": "stop_date",
    "target": "price_target",
    "target_currency": "target_currency",
    "target_horizon_mo": "target_horizon_months",
    "target_price": "price_target",
    "ticker": "vendor_security_id",
    "tic": "symbol",
    "value": "price_target",
}

RECOMMENDATION_SUMMARY_COLUMN_ALIASES = {
    "asof": "as_of_date",
    "available_date": "available_date",
    "best_analyst_rating": "mean_recommendation",
    "best_analyst_recs": "total_recommendations",
    "best_recs_buys": "buy_equivalent_count",
    "best_recs_holds": "hold_count",
    "best_recs_sells": "sell_equivalent_count",
    "best_target_price": "mean_price_target",
    "buy": "buy_count",
    "buy_count": "buy_count",
    "buy_equivalent": "buy_equivalent_count",
    "buy_equivalent_count": "buy_equivalent_count",
    "buys": "buy_count",
    "consensus_date": "snapshot_date",
    "curr": "target_currency",
    "estcur": "target_currency",
    "highptg": "high_price_target",
    "hold": "hold_count",
    "hold_count": "hold_count",
    "holds": "hold_count",
    "horizon": "target_horizon_months",
    "ibes_ticker": "vendor_security_id",
    "lowptg": "low_price_target",
    "mean_ptg": "mean_price_target",
    "mean_rating": "mean_recommendation",
    "mean_recommendation": "mean_recommendation",
    "meanptg": "mean_price_target",
    "meanrec": "mean_recommendation",
    "med_ptg": "median_price_target",
    "median_rating": "median_recommendation",
    "median_recommendation": "median_recommendation",
    "medptg": "median_price_target",
    "medrec": "median_recommendation",
    "num_buy": "buy_count",
    "num_buys": "buy_count",
    "num_hold": "hold_count",
    "num_holds": "hold_count",
    "num_ptg": "price_target_count",
    "num_rec": "total_recommendations",
    "num_recommendations": "total_recommendations",
    "num_sell": "sell_count",
    "num_sells": "sell_count",
    "num_strong_buy": "strong_buy_count",
    "num_strong_buys": "strong_buy_count",
    "num_underperform": "underperform_count",
    "num_underperforms": "underperform_count",
    "numptg": "price_target_count",
    "numrec": "total_recommendations",
    "oftic": "symbol",
    "official_ticker": "symbol",
    "ptg_count": "price_target_count",
    "rating_count": "total_recommendations",
    "recs_buys": "buy_equivalent_count",
    "recs_holds": "hold_count",
    "recs_sells": "sell_equivalent_count",
    "sell": "sell_count",
    "sell_count": "sell_count",
    "sell_equivalent": "sell_equivalent_count",
    "sell_equivalent_count": "sell_equivalent_count",
    "sells": "sell_count",
    "snapshot_date": "snapshot_date",
    "source_table": "source_vendor_table",
    "statpers": "snapshot_date",
    "strong_buy": "strong_buy_count",
    "strong_buy_count": "strong_buy_count",
    "strong_buys": "strong_buy_count",
    "target": "mean_price_target",
    "target_currency": "target_currency",
    "target_horizon_mo": "target_horizon_months",
    "target_price": "mean_price_target",
    "ticker": "vendor_security_id",
    "tic": "symbol",
    "underperform": "underperform_count",
    "underperform_count": "underperform_count",
    "underperforms": "underperform_count",
}

RECOMMENDATION_LABELS = {
    1: "Strong Buy",
    2: "Buy",
    3: "Hold",
    4: "Underperform",
    5: "Sell",
}

RECOMMENDATION_TEXT_MAP = {
    "ACCUMULATE": 2,
    "ADD": 2,
    "BUY": 2,
    "EQUAL-WEIGHT": 3,
    "EQUAL WEIGHT": 3,
    "HOLD": 3,
    "MARKET PERFORM": 3,
    "MARKET-PERFORM": 3,
    "NEUTRAL": 3,
    "OUTPERFORM": 2,
    "OUTPERFORMER": 2,
    "OVERWEIGHT": 2,
    "REDUCE": 4,
    "SECTOR PERFORM": 3,
    "SECTOR-PERFORM": 3,
    "SELL": 5,
    "STRONG BUY": 1,
    "STRONG-BUY": 1,
    "STRONG SELL": 5,
    "STRONG-SELL": 5,
    "UNDERPERFORM": 4,
    "UNDERPERFORMER": 4,
    "UNDERWEIGHT": 4,
}

IBES_MEASURE_MAP = {
    "SAL": "REVENUE",
    "SALES": "REVENUE",
    "REV": "REVENUE",
    "NET": "NET_INCOME",
    "INC": "NET_INCOME",
    "NI": "NET_INCOME",
    "OPR": "OPERATING_INCOME",
}

GUIDANCE_COLUMN_ALIASES = {
    "acceptancedatetime": "acceptance_datetime",
    "accession": "accession_number",
    "accessionnumber": "accession_number",
    "confidence": "extraction_confidence",
    "content": "document_text",
    "document": "document_text",
    "documenttext": "document_text",
    "exhibittext": "document_text",
    "extractionconfidence": "extraction_confidence",
    "filingdate": "filing_date",
    "fiscalperiod": "fiscal_period",
    "fiscalyear": "fiscal_year",
    "guidancecurrency": "currency",
    "guidancedate": "guidance_date",
    "guidancehigh": "high",
    "guidancelow": "low",
    "guidancemid": "mid",
    "guidancepoint": "mid",
    "guidancetype": "guidance_type",
    "item": "source_item",
    "measure": "measure_code",
    "measurecode": "measure_code",
    "periodend": "period_end",
    "rawtext": "document_text",
    "reportdate": "report_date",
    "securityid": "security_id",
    "sourceitem": "source_item",
    "sourceurl": "source_url",
    "ticker": "symbol",
    "unitsscale": "units_scale",
}

GUIDANCE_TEXT_COLUMNS = ("document_text", "text", "raw_text", "content", "exhibit_text")

GUIDANCE_SOURCE_CUE_RE = re.compile(
    r"\b(expects?|anticipates?|projects?|forecasts?|outlook|guidance|"
    r"raises?|reaffirms?|targets?|sees)\b",
    flags=re.IGNORECASE,
)
GUIDANCE_VALUE_RE = re.compile(
    r"(?P<currency>\$)?\s*(?P<number>\d[\d,]*(?:\.\d+)?)\s*"
    r"(?P<unit>billion|bn|million|mm|m|thousand|k)?\b",
    flags=re.IGNORECASE,
)
GUIDANCE_MEASURE_PATTERNS = (
    (
        "EPS_DILUTED",
        re.compile(
            r"\b(?:non-gaap\s+|adjusted\s+|gaap\s+)?(?:diluted\s+)?"
            r"(?:eps|earnings\s+per\s+share)\b",
            flags=re.IGNORECASE,
        ),
    ),
    ("OPERATING_INCOME", re.compile(r"\boperating\s+income\b", flags=re.IGNORECASE)),
    ("NET_INCOME", re.compile(r"\bnet\s+income\b", flags=re.IGNORECASE)),
    ("REVENUE", re.compile(r"\b(?:revenue|revenues|sales)\b", flags=re.IGNORECASE)),
)

__all__ = [
    "_MEASURE_ROWS",
    "ESTIMATE_DETAIL_COLUMNS",
    "ESTIMATE_BROKER_COLUMNS",
    "ESTIMATE_ANALYST_COLUMNS",
    "ESTIMATE_PERIOD_COLUMNS",
    "ESTIMATE_BROKER_ALIAS_COLUMNS",
    "ESTIMATE_ANALYST_ALIAS_COLUMNS",
    "ESTIMATE_CONSENSUS_COLUMNS",
    "ESTIMATE_GUIDANCE_COLUMNS",
    "ESTIMATE_RECOMMENDATION_COLUMNS",
    "ESTIMATE_RECOMMENDATION_SUMMARY_COLUMNS",
    "DETAIL_COLUMN_ALIASES",
    "CONSENSUS_COLUMN_ALIASES",
    "RECOMMENDATION_COLUMN_ALIASES",
    "RECOMMENDATION_SUMMARY_COLUMN_ALIASES",
    "RECOMMENDATION_LABELS",
    "RECOMMENDATION_TEXT_MAP",
    "IBES_MEASURE_MAP",
    "GUIDANCE_COLUMN_ALIASES",
    "GUIDANCE_TEXT_COLUMNS",
    "GUIDANCE_SOURCE_CUE_RE",
    "GUIDANCE_VALUE_RE",
    "GUIDANCE_MEASURE_PATTERNS",
]
