#!/usr/bin/env python3
"""One spec-driven library generator (platform core migration slice 2, Ruling PM8-12).

  generate_from_spec.py --spec SPEC (--check | --out DIR) [--plan-json PATH] [--strategies DIR]

A library version is data, not a Python file: this wrapper replaces the generate_fund_ic_v*.py lineage. It reads
SPEC (atx.library-spec/v1, e.g. specs/library-v71.json):
  library        the definition libraries/<library>.json, built from alphas/registry.json by generate_library.py's
                 builders (one implementation, imported, not copied)
  registry_pins  {"house_budget": {...}}: registry values as of the version (the slim recipe records them, so a later
                 registry edit must not move an old version's bytes)
  outputs        {file name: sha256 | null}: every generated artefact; null = not pinned yet (a new version:
                 --out writes it and its receipt; --check refuses it)
  frozen         {file name: sha256}: committed artefacts no program regenerates any more (the legacy lineage's
                 libraries and provenance recipes), verified byte for byte
  plan           {"json": path} (a saved `atx-equity-strategy-ic --plan-only` output) or {"exe": {exe, train,
                 train_sha256, train_fields, train_fields_sha256[, max_memory_mib]}}: the K1 static validation, made by
                 the engine's IC executable on the generated library, never by a Python parser
  replaces, note optional documentation (the generators this spec supersedes)
--check compares the generated bytes with the committed files under the strategies dir; --out DIR writes the
artefacts and receipt.json there. --plan-json overrides the spec's plan (root: the exe's live output).
Exit 0 ok; 1 an artefact, a pin or the plan disagrees; 2 a bad spec or input.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path
import re
import sys
import tempfile

import generate_library as G

HERE = Path(__file__).resolve().parent
SPEC_SCHEMA = "atx.library-spec/v1"
RECEIPT_SCHEMA = "atx.library-spec-receipt/v1"
SPEC_KEYS = ("schema", "library", "registry_pins", "outputs", "frozen", "plan")
SPEC_OPTIONAL = ("replaces", "note")
EXE_KEYS = ("exe", "train", "train_sha256", "train_fields", "train_fields_sha256")
SHA_RE = re.compile(r"[0-9a-f]{64}")
NAME_RE = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]*")


class SpecError(ValueError):
    pass


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def check_names(spec: dict, key: str, allow_null: bool) -> None:
    pins = spec[key]
    if not isinstance(pins, dict) or not all(isinstance(n, str) and NAME_RE.fullmatch(n) for n in pins) or not all(
            (allow_null and v is None) or (isinstance(v, str) and SHA_RE.fullmatch(v)) for v in pins.values()):
        raise SpecError(f"spec {key}: {{file name next to the generator: lower-case sha256"
                        f"{' or null' if allow_null else ''}}}")


def validate_spec(spec) -> dict:
    if not isinstance(spec, dict) or spec.get("schema") != SPEC_SCHEMA:
        raise SpecError(f"spec schema must be {SPEC_SCHEMA}")
    if not set(SPEC_KEYS) <= set(spec) <= set(SPEC_KEYS + SPEC_OPTIONAL):
        raise SpecError(f"spec keys must be {', '.join(SPEC_KEYS)} (optional {', '.join(SPEC_OPTIONAL)})")
    if not isinstance(spec["library"], str) or not G.ID_RE.fullmatch(spec["library"]):
        raise SpecError(f"spec library must name libraries/<name>.json ({G.ID_RE.pattern})")
    pins = spec["registry_pins"]
    house = pins.get("house_budget", {}) if isinstance(pins, dict) else None
    if not isinstance(pins, dict) or not set(pins) <= {"house_budget"} or not isinstance(house, dict) or \
            not set(house) <= set(G.HOUSE_KEYS) or not all(type(v) is int and v > 0 for v in house.values()):
        raise SpecError(f"spec registry_pins: {{house_budget: positive integers among {', '.join(G.HOUSE_KEYS)}}}")
    check_names(spec, "outputs", allow_null=True)
    check_names(spec, "frozen", allow_null=False)
    if set(spec["outputs"]) & set(spec["frozen"]):
        raise SpecError("spec: a file is either generated (outputs) or frozen, not both")
    plan = spec["plan"]
    exe = plan.get("exe") if isinstance(plan, dict) else None
    if not isinstance(plan, dict) or len(plan) != 1 or not (
            isinstance(plan.get("json"), str) or (isinstance(exe, dict) and set(EXE_KEYS) <= set(exe) <=
                                                  set(EXE_KEYS) | {"max_memory_mib"})):
        raise SpecError(f"spec plan: {{json: path}} or {{exe: {{{', '.join(EXE_KEYS)}[, max_memory_mib]}}}}")
    return spec


def pinned_registry(root: Path, spec: dict) -> dict:
    """The registry with the spec's pins applied (in memory; the file is not edited), validated again."""
    reg = copy.deepcopy(G.load_registry(root))
    reg["house_budget"].update(spec["registry_pins"].get("house_budget", {}))
    return G.validate_registry(reg)


def make_plan(root: Path, spec: dict, library_name: str, library_bytes: bytes, plan_json: Path | None):
    """(plan JSON, its source): the K1 rows of the generated library, from the IC exe or a saved output of it."""
    if plan_json is not None:
        return G.load_json(plan_json), str(plan_json)
    if "json" in spec["plan"]:
        return G.load_json(root / spec["plan"]["json"]), spec["plan"]["json"]
    e = spec["plan"]["exe"]
    with tempfile.TemporaryDirectory() as tmp:
        library = Path(tmp) / library_name
        library.write_bytes(library_bytes)
        plan = G.exe_plan(e["exe"], library, e["train"], e["train_sha256"], e["train_fields"],
                          e["train_fields_sha256"], cwd=root, max_memory_mib=e.get("max_memory_mib"))
    return plan, f"{e['exe']} --plan-only"


def problems_of(root: Path, spec: dict, docs: dict[str, bytes], check: bool) -> list[str]:
    out = []
    if set(docs) != set(spec["outputs"]):
        out.append(f"generated {sorted(docs)}, the spec's outputs name {sorted(spec['outputs'])}")
    for name, blob in docs.items():
        pin = spec["outputs"].get(name)
        if pin is None and check:
            out.append(f"{name}: not pinned (sha256 {sha256(blob)}); --check needs every output pinned")
        elif pin is not None and sha256(blob) != pin:
            out.append(f"{name}: generated sha256 {sha256(blob)}, the spec pins {pin}")
        if check and (not (root / name).is_file() or (root / name).read_bytes() != blob):
            out.append(f"{name}: generated bytes differ from the committed file")
    for name, pin in spec["frozen"].items():
        path = root / name
        got = sha256(path.read_bytes()) if path.is_file() else "missing"
        if got != pin:
            out.append(f"frozen {name}: sha256 {got}, the spec pins {pin}")
    return out


def receipt(spec_path: Path, spec_bytes: bytes, spec: dict, docs: dict[str, bytes], source: str, rows: int) -> dict:
    own = Path(__file__).read_bytes().replace(b"\r\n", b"\n")
    return dict(schema=RECEIPT_SCHEMA, spec=dict(path=str(spec_path), sha256=sha256(spec_bytes)),
                generator=dict(path="generate_from_spec.py", sha256_lf=sha256(own),
                               builders="generate_library.py", builders_sha256_lf=sha256(
                                   Path(G.__file__).read_bytes().replace(b"\r\n", b"\n"))),
                library=spec["library"], registry_pins=spec["registry_pins"],
                outputs={n: dict(sha256=sha256(b), bytes=len(b)) for n, b in docs.items()},
                frozen_verified=sorted(spec["frozen"]), plan=dict(source=source, rows=rows))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0], epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", type=Path, required=True, help="the library spec (atx.library-spec/v1)")
    ap.add_argument("--check", action="store_true", help="compare the committed files instead of writing")
    ap.add_argument("--out", type=Path, default=None, help="write the artefacts and receipt.json into DIR")
    ap.add_argument("--plan-json", type=Path, default=None, help="the IC exe's --plan-only JSON (overrides the spec)")
    ap.add_argument("--strategies", type=Path, default=HERE, help=argparse.SUPPRESS)
    a = ap.parse_args(argv)
    if a.check == (a.out is not None):
        print("generate_from_spec: pass exactly one of --check and --out DIR", file=sys.stderr)
        return 2
    try:
        root = Path(a.strategies)
        spec_path = a.spec if a.spec.is_absolute() or a.spec.is_file() else root / a.spec
        spec_bytes = spec_path.read_bytes()
        spec = validate_spec(json.loads(spec_bytes.decode("utf-8")))
        reg = pinned_registry(root, spec)
        lib = G.load_library(root, spec["library"])
        docs = G.documents(root, spec["library"], reg)
        lib_name = G.output_names(lib)[0]
        plan, source = make_plan(root, spec, lib_name, docs[lib_name], a.plan_json)
        problems = problems_of(root, spec, docs, a.check)
        problems += G.validate_plan(reg, lib, json.loads(docs[lib_name]), docs[lib_name], plan)
        for p in problems:
            print(f"generate_from_spec: {p}", file=sys.stderr)
        if problems:
            return 1
        rows = len(G.plan_rows(plan))
        if a.out is not None:
            a.out.mkdir(parents=True, exist_ok=True)
            for name, blob in docs.items():
                (a.out / name).write_bytes(blob)
            (a.out / "receipt.json").write_bytes(G.encode(receipt(spec_path, spec_bytes, spec, docs, source, rows)))
        for name, blob in docs.items():
            print(f"{name} {sha256(blob)} {len(blob)} bytes")
        print(f"frozen: {len(spec['frozen'])} artefacts verified; plan ({source}): {rows} K1 rows within budget")
        return 0
    except (SpecError, G.LibraryError, OSError, ValueError) as exc:
        print(f"generate_from_spec: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
