#include <algorithm>
#include <array>
#include <atomic>
#include <bit>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <limits>
#include <span>
#include <sstream>
#include <stdexcept>
#include <string>
#include <system_error>
#include <utility>
#include <vector>
#include <gtest/gtest.h>
#include <nlohmann/json.hpp>
#include "atx/core/sha256.hpp"
#include "../src/strategy_exposures_verb.hpp"
#include "../src/strategy_price_exposures.hpp"

// v8 D-2 (contract K2): the `exposures` verb exports the fitter's price-risk context from the
// C++ exposures. The golden values below are fit_composition_weights.py's own output
// (PricePanel, neutralization_basis, Context.build/book/factor_returns) on the fixture that
// fitter_fixture() builds, generated by the pytest test_exposures_export.py, which pins the
// same numbers against the fitter's code.
namespace {
using namespace atx;
namespace st = atx::impl::strategy;
namespace co = atx::core;
using Json = nlohmann::json;
constexpr f64 missing = std::numeric_limits<f64>::quiet_NaN();
constexpr usize kBasis = st::kBasisColumns;

struct Lcg {
  u64 state{};
  f64 next() { // [0, 1)
    state = state * 6364136223846793005ULL + 1442695040888963407ULL;
    return static_cast<f64>(state >> 11) * 0x1.0p-53;
  }
};
// test_exposures_export.py fixture(), operation for operation: a one-factor walk with
// per-name loadings, an adjusted-only doubling of name 5 from session 150 (interval 150
// guarded), scattered absent rows, 15 names absent at session 140 (fewer than 50 used names
// at decision 140: refused), scattered nonmembers, and two signals (s1 noise with NaN
// cells, s2 loading on the factor loading).
constexpr usize kD = 170, kN = 60, kBegin = 130, kRefusedSession = 140;
struct Fixture {
  usize dates{}, names{};
  std::vector<f64> close, raw, volume, s1, s2;
  std::vector<u8> present, member;
  [[nodiscard]] st::PriceExposureInput input() const {
    return {dates, names, close, raw, volume, present};
  }
};
Fixture fitter_fixture(usize dates = kD, usize member_from = 0) {
  Fixture f;
  f.dates = dates; f.names = kN;
  const usize cells = dates * kN;
  f.close.assign(cells, 0.0);
  Lcg rng{2026};
  for (usize i = 0; i < kN; ++i) f.close[i] = 20.0 + static_cast<f64>(i);
  for (usize t = 1; t < dates; ++t) {
    const f64 common = 0.03 * (rng.next() - 0.5);
    for (usize i = 0; i < kN; ++i) {
      const f64 loading = 0.5 + 0.02 * static_cast<f64>(i);
      const f64 idio = 0.005 + 0.0002 * static_cast<f64>((i * 7) % kN);
      f.close[t * kN + i] =
          f.close[(t - 1) * kN + i] * (1 + loading * common + idio * (rng.next() - 0.5));
    }
  }
  f.raw = f.close;
  for (usize t = 150; t < dates; ++t) f.close[t * kN + 5] = f.close[t * kN + 5] * 2.0;
  f.volume.assign(cells, 0.0);
  for (usize t = 0; t < dates; ++t)
    for (usize i = 0; i < kN; ++i)
      f.volume[t * kN + i] =
          1e4 * static_cast<f64>(1 + (i * 11) % kN) * (0.5 + rng.next());
  f.present.assign(cells, 1);
  f.member.assign(cells, 0);
  for (usize t = 0; t < dates; ++t)
    for (usize i = 0; i < kN; ++i) {
      const usize k = t * kN + i;
      if ((t * 7 + i * 3) % 97 == 0 || (t == kRefusedSession && i < 15)) f.present[k] = 0;
      f.member[k] = static_cast<u8>(f.present[k] && (t + 2 * i) % 19 != 0 && t >= member_from);
      if (!f.present[k]) f.close[k] = f.raw[k] = f.volume[k] = missing;
    }
  f.s1.assign(cells, 0.0);
  f.s2.assign(cells, 0.0);
  Lcg draws{77};
  for (usize t = 0; t < dates; ++t)
    for (usize i = 0; i < kN; ++i) {
      const usize k = t * kN + i;
      f.s1[k] = draws.next() - 0.5;
      f.s2[k] = (0.5 + 0.02 * static_cast<f64>(i)) + 0.2 * (draws.next() - 0.5);
      if ((t * 3 + i) % 23 == 0) f.s1[k] = missing;
    }
  return f;
}
// The export of decisions [begin, end) in memory.
struct Export {
  std::vector<f64> basis, forward;
  std::vector<st::ExposureDecision> decisions;
};
Export export_all(const Fixture& f, usize begin, usize end, bool ring = true) {
  Export out;
  const auto panel = f.input();
  st::ExposureExportScratch scratch;
  if (ring) st::enable_session_ring(scratch.exposure, panel);
  std::vector<f64> basis(kN * kBasis), forward(kN);
  for (usize d = begin; d < end; ++d) {
    const auto decision = st::export_decision(panel, f.member, st::PriceExposureConfig{}, d,
                                              scratch, basis, forward);
    EXPECT_TRUE(decision) << d << ' ' << (decision ? std::string{} : decision.error().to_string());
    if (!decision) return out;
    out.decisions.push_back(*decision);
    out.basis.insert(out.basis.end(), basis.begin(), basis.end());
    out.forward.insert(out.forward.end(), forward.begin(), forward.end());
  }
  return out;
}
// fit_composition_weights.py centered_tied_ranks for one row: over the valid cells, a tie
// group [b, e) of the ascending order gets (b + (e - 1)) / (2 (n - 1)) - 0.5; 0 elsewhere
// and on rows with fewer than two valid cells.
std::vector<f64> centered_ranks(std::span<const f64> x, const std::vector<u8>& valid) {
  std::vector<usize> order;
  for (usize i = 0; i < x.size(); ++i)
    if (valid[i]) order.push_back(i);
  std::vector<f64> out(x.size(), 0.0);
  const usize n = order.size();
  if (n < 2) return out;
  std::sort(order.begin(), order.end(), [&](usize a, usize b) { return x[a] < x[b]; });
  for (usize b = 0; b < n;) {
    usize e = b + 1;
    while (e < n && x[order[e]] == x[order[b]]) ++e;
    const f64 rank = (static_cast<f64>(b) + static_cast<f64>(e - 1)) /
                     (2.0 * static_cast<f64>(n - 1)) - 0.5;
    for (usize k = b; k < e; ++k) out[order[k]] = rank;
    b = e;
  }
  return out;
}
// The fitter's Context.book + factor_returns on one exported decision: ranks over the used
// names with a finite signal, projected out of the basis twice (one refinement, as the fitter),
// gross 1 when live (entry > 0, finite gross > 1e-9 entry), f = sum q fwd (NaN fwd as 0).
struct Factor {
  bool live{};
  f64 value{};
};
Factor fitter_factor(std::span<const f64> basis, std::span<const f64> forward,
                     std::span<const f64> signal) {
  const usize n = signal.size();
  std::vector<u8> valid(n);
  for (usize i = 0; i < n; ++i)
    valid[i] = static_cast<u8>(basis[i * kBasis] != 0 && std::isfinite(signal[i]));
  auto x = centered_ranks(signal, valid);
  f64 entry = 0;
  for (const f64 v : x) entry += std::abs(v);
  for (int pass = 0; pass < 2; ++pass) {
    std::array<f64, kBasis> coef{};
    for (usize k = 0; k < kBasis; ++k)
      for (usize i = 0; i < n; ++i) coef[k] += basis[i * kBasis + k] * x[i];
    for (usize i = 0; i < n; ++i)
      for (usize k = 0; k < kBasis; ++k) x[i] -= basis[i * kBasis + k] * coef[k];
  }
  f64 gross = 0;
  for (const f64 v : x) gross += std::abs(v);
  Factor out;
  out.live = entry > 0 && std::isfinite(gross) && gross > 1e-9 * entry;
  if (!out.live) return out;
  for (usize i = 0; i < n; ++i)
    out.value += x[i] / gross * (std::isnan(forward[i]) ? 0.0 : forward[i]);
  return out;
}
bool same_bits(std::span<const f64> a, std::span<const f64> b) {
  if (a.size() != b.size()) return false;
  for (usize k = 0; k < a.size(); ++k)
    if (std::bit_cast<u64>(a[k]) != std::bit_cast<u64>(b[k])) return false;
  return true;
}

// fit_composition_weights.py on fitter_fixture() (test_exposures_export.py prints these).
constexpr std::array<usize, 38> kFitterUsedRows{
    56, 55, 57, 55, 56, 57, 56, 57, 57, 57, 0, 56, 57, 56, 56, 57, 56, 56, 56,
    56, 55, 57, 55, 56, 57, 57, 56, 56, 57, 56, 56, 57, 56, 56, 57, 57, 56, 56};
constexpr std::array<f64, 38> kFitterS1{
    -9.19198784463074e-05, 0.0008272532032060129, -0.0006079351944851783,
    5.6292759506600254e-05, 0.00021530213310144936, -0.0004560599685223116,
    8.402816008971346e-05, 0.00027696122061903264, -0.0005221995413579406,
    -0.0007193637666926997, missing, 4.4007755157138895e-05,
    -0.0001704131194949057, -0.0007014630433080914, 0.0004614346945631002,
    -0.000807734669379995, -0.0007694719760383647, 9.883956453911498e-05,
    0.0007298879826759359, -0.0005058364949033298, 0.0004101879476274091,
    -0.0001533071279159201, 0.0007577682616694754, 0.00010605348115144307,
    0.0008948913863852869, -0.0010002138830198122, -0.0008698488095141693,
    -0.00016653844360498728, 0.00029905651005841295, 0.0009468310088160122,
    -0.0002663447797392951, 6.034453590344906e-05, 0.0008209286899430078,
    -0.001077964340981195, -0.00036054833152376876, 0.00018654550554119282,
    -0.00010471336688552656, -0.0002835192531504609};
constexpr std::array<f64, 38> kFitterS2{
    -0.0008799701294914398, -0.00023888193463026005, 0.0002415709411591965,
    -0.0006838404234326478, 8.949319509674569e-05, -0.0011627369661886386,
    0.000184829992376929, -0.0006156575220706606, 0.00011905297295288326,
    0.0005709543080931095, missing, -0.00030240597103093844,
    0.0005685060167781637, 0.0002737970960780321, 0.0001551336046395191,
    0.0008324525021018484, 4.27094261883143e-05, 0.00037246734623502266,
    0.00018115339282483918, 0.00039264873252129633, 0.0005531381152531211,
    0.0002920287851569611, 0.00011912418370547885, -0.0001860625267872974,
    0.0010553327580915639, 3.617233167820948e-05, 0.00042710448052081594,
    0.0008845591119457407, -0.000212479296749472, 5.729934546512883e-05,
    0.0002067746617271831, 0.000428652826469272, 0.001045962946689331,
    0.000256597102147776, -0.0008289457912662962, 0.0002979492527342877,
    -0.00040936529189976783, -0.000926430092093695};
// Rows of the fitter's Q (numpy.linalg.qr): {decision offset, name, [q_1, q_beta, q_vol, q_ladv]}.
struct BasisRow {
  usize offset{}, name{};
  std::array<f64, 4> q{};
};
constexpr std::array<BasisRow, 6> kFitterBasis{{
    {0, 0, {-0.13363062095621214, -0.22182078079274928, -0.19119898546057393,
            0.4808685504974287}},
    {0, 1, {-0.1336306209562122, -0.2174061211143507, -0.1520251866475545,
            0.08194268061361197}},
    {20, 0, {-0.13483997249264834, -0.22688453035224784, 0.17760100935973644,
             0.45851573839113324}},
    {20, 2, {-0.13483997249264842, -0.21196786986891764, 0.06540771099177016,
             -0.008841865937676578}},
    {37, 0, {-0.13363062095621214, -0.22861396961780076, 0.1619200474843727,
             0.45038210144590074}},
    {37, 1, {-0.1336306209562122, -0.22043027174384858, 0.10622175848416804,
             0.08311543747735738}}}};
} // namespace

// The fitter's factor series, computed from the export exactly as the fitter computes it from
// its own context (Context.book, factor_returns), equals the fitter's own output to 1e-12 for
// a noise signal and a signal loading on beta; the live days, the used rows, the refused
// decision (too-few-usable-names, 42 rows) and the basis rows themselves (numpy's QR sign
// convention) agree; Q is orthonormal on the used rows and 0 elsewhere; the ring and the
// stateless exposures export the same bits.
TEST(Exposures, FitterFactorsEqualTo1e12) {
  const auto f = fitter_fixture();
  const usize end = kD - 2, decisions = end - kBegin;
  const auto ex = export_all(f, kBegin, end);
  ASSERT_EQ(ex.decisions.size(), decisions);
  for (usize j = 0; j < decisions; ++j) {
    const auto& decision = ex.decisions[j];
    const bool refused = kBegin + j == kRefusedSession;
    EXPECT_EQ(decision.refusal, refused ? st::BasisRefusal::TooFewNames : st::BasisRefusal::None)
        << j;
    EXPECT_EQ(refused ? usize{0} : decision.used_rows, kFitterUsedRows[j]) << j;
  }
  EXPECT_EQ(ex.decisions[kRefusedSession - kBegin].used_rows, 42U);
  EXPECT_STREQ(st::basis_refusal_id(st::BasisRefusal::TooFewNames), "too-few-usable-names");
  const auto basis_of = [&](usize j) {
    return std::span<const f64>(ex.basis).subspan(j * kN * kBasis, kN * kBasis);
  };
  const auto forward_of = [&](usize j) {
    return std::span<const f64>(ex.forward).subspan(j * kN, kN);
  };
  for (const auto& [signal, golden] :
       {std::pair{&f.s1, &kFitterS1}, std::pair{&f.s2, &kFitterS2}})
    for (usize j = 0; j < decisions; ++j) {
      const auto row = std::span<const f64>(*signal).subspan((kBegin + j) * kN, kN);
      const auto factor = fitter_factor(basis_of(j), forward_of(j), row);
      const f64 expected = (*golden)[j];
      ASSERT_EQ(factor.live, !std::isnan(expected)) << j;
      if (factor.live) EXPECT_NEAR(factor.value, expected, 1e-12) << j;
    }
  for (const auto& row : kFitterBasis)
    for (usize k = 0; k < kBasis; ++k)
      EXPECT_NEAR(basis_of(row.offset)[row.name * kBasis + k], row.q[k], 1e-12)
          << row.offset << ' ' << row.name << ' ' << k;
  for (usize j = 0; j < decisions; ++j) {
    const auto q = basis_of(j);
    usize used = 0;
    for (usize i = 0; i < kN; ++i) used += q[i * kBasis] != 0 ? 1U : 0U;
    EXPECT_EQ(used, kFitterUsedRows[j]) << j;
    for (usize a = 0; a < kBasis; ++a)
      for (usize b = 0; b < kBasis; ++b) {
        f64 dot = 0;
        for (usize i = 0; i < kN; ++i) dot += q[i * kBasis + a] * q[i * kBasis + b];
        if (used) EXPECT_NEAR(dot, a == b ? 1.0 : 0.0, 1e-12) << j;
      }
  }
  // Interval 150 of name 5 is guarded (adjusted-only doubling): decision 148's label is NaN.
  EXPECT_TRUE(std::isnan(forward_of(148 - kBegin)[5]));
  EXPECT_FALSE(std::isnan(forward_of(147 - kBegin)[5]));
  const auto stateless = export_all(f, kBegin, end, false);
  EXPECT_TRUE(same_bits(stateless.basis, ex.basis));
  EXPECT_TRUE(same_bits(stateless.forward, ex.forward));
}

// neutralization_basis: an orthonormal Q whose projection residual is neutralize_target's OLS
// residual (rescaled to the same gross) to 1e-12; the first column is -1/sqrt(m) (LAPACK's
// sign); refusals in the fitter's order and names; geometry errors.
TEST(Exposures, BasisIsTheOlsProjectionAndRefusesLikeTheFitter) {
  constexpr usize n = 64;
  Lcg rng{9};
  std::vector<f64> exposures(n * st::kPriceExposureCount);
  for (usize i = 0; i < n; ++i) {
    exposures[i * 3 + st::kExposureBeta] = 0.3 + 1.2 * rng.next();
    exposures[i * 3 + st::kExposureVol] = 0.01 + 0.03 * rng.next();
    exposures[i * 3 + st::kExposureLogAdv] = 12.0 + 6.0 * rng.next();
  }
  std::vector<usize> rows;
  for (usize i = 0; i < n; ++i)
    if (i % 9 != 4) rows.push_back(i); // 57 used rows
  const usize m = rows.size();
  const st::PriceExposureConfig cfg{};
  st::NeutralizeScratch scratch;
  std::vector<f64> q(m * kBasis);
  const auto made = st::neutralization_basis(exposures, rows, cfg, scratch, q);
  ASSERT_TRUE(made) << made.error().to_string();
  ASSERT_EQ(*made, st::BasisRefusal::None);
  for (usize r = 0; r < m; ++r)
    EXPECT_NEAR(q[r * kBasis], -1.0 / std::sqrt(static_cast<f64>(m)), 1e-15) << r;
  // A target on the used rows (members = used rows, every row ok): the projection residual,
  // rescaled to the entry gross, is neutralize_target's result.
  std::vector<f64> target(n, 0.0);
  std::vector<u8> member(n, 0), ok(n, 1);
  for (const usize i : rows) {
    member[i] = 1;
    target[i] = exposures[i * 3] + (rng.next() - 0.5);
  }
  f64 mean = 0;
  for (const usize i : rows) mean += target[i] / static_cast<f64>(m);
  for (const usize i : rows) target[i] -= mean;
  auto neutral = target;
  st::NeutralizeStats stats;
  ASSERT_TRUE(st::neutralize_target(neutral, member, exposures, ok, cfg, scratch, stats));
  std::vector<f64> x(m);
  f64 entry = 0;
  for (usize r = 0; r < m; ++r) { x[r] = target[rows[r]]; entry += std::abs(x[r]); }
  for (int pass = 0; pass < 2; ++pass) {
    std::array<f64, kBasis> coef{};
    for (usize k = 0; k < kBasis; ++k)
      for (usize r = 0; r < m; ++r) coef[k] += q[r * kBasis + k] * x[r];
    for (usize r = 0; r < m; ++r)
      for (usize k = 0; k < kBasis; ++k) x[r] -= q[r * kBasis + k] * coef[k];
  }
  f64 gross = 0;
  for (const f64 v : x) gross += std::abs(v);
  for (usize r = 0; r < m; ++r)
    EXPECT_NEAR(x[r] * entry / gross, neutral[rows[r]], 1e-12) << r;
  const auto refusal = [&](std::vector<f64> e, std::vector<usize> used) {
    std::vector<f64> out(used.size() * kBasis);
    const auto r = st::neutralization_basis(e, used, cfg, scratch, out);
    EXPECT_TRUE(r) << (r ? std::string{} : r.error().to_string());
    return r ? *r : st::BasisRefusal::None;
  };
  EXPECT_EQ(refusal(exposures, std::vector<usize>(rows.begin(), rows.begin() + 49)),
            st::BasisRefusal::TooFewNames);
  auto constant = exposures;
  for (usize i = 0; i < n; ++i) constant[i * 3 + st::kExposureVol] = 0.02;
  EXPECT_EQ(refusal(constant, rows), st::BasisRefusal::ConstantExposure);
  auto collinear = exposures;
  for (usize i = 0; i < n; ++i)
    collinear[i * 3 + st::kExposureLogAdv] = 2.0 * collinear[i * 3 + st::kExposureBeta] + 1.0;
  EXPECT_EQ(refusal(collinear, rows), st::BasisRefusal::IllConditioned);
  EXPECT_STREQ(st::basis_refusal_id(st::BasisRefusal::ConstantExposure), "constant-exposure");
  EXPECT_STREQ(st::basis_refusal_id(st::BasisRefusal::IllConditioned),
               "ill-conditioned-exposures");
  EXPECT_STREQ(st::basis_refusal_id(st::BasisRefusal::None), "");
  std::vector<f64> short_basis(m * kBasis - 1);
  auto backwards = rows;
  std::swap(backwards[0], backwards[1]);
  auto bad = exposures;
  bad[rows[3] * 3] = missing;
  for (const auto& status :
       {st::neutralization_basis(exposures, rows, cfg, scratch, short_basis),
        st::neutralization_basis(exposures, backwards, cfg, scratch, q),
        st::neutralization_basis(bad, rows, cfg, scratch, q)}) {
    ASSERT_FALSE(status);
    EXPECT_EQ(status.error().code(), co::ErrorCode::InvalidArgument);
  }
}

namespace {
struct Directory {
  std::filesystem::path path;
  Directory() {
    static std::atomic<u64> counter{0};
    const auto tick = std::chrono::steady_clock::now().time_since_epoch().count();
    path = std::filesystem::temp_directory_path() /
        ("atx_exposures_" + std::to_string(tick) + "_" + std::to_string(counter.fetch_add(1)));
    if (!std::filesystem::create_directory(path)) throw std::runtime_error("fixture directory");
  }
  ~Directory() { std::error_code ec; std::filesystem::remove_all(path, ec); }
  Directory(const Directory&) = delete;
  Directory& operator=(const Directory&) = delete;
};
template <class T> Json payload(const std::filesystem::path& file, const std::vector<T>& data) {
  std::ofstream out(file, std::ios::binary);
  const auto bytes = std::as_bytes(std::span(data));
  // SAFETY: char writes the object representation of contiguous arithmetic fixture data.
  out.write(reinterpret_cast<const char*>(bytes.data()),
            static_cast<std::streamsize>(bytes.size()));
  out.close();
  if (!out) throw std::runtime_error("fixture payload");
  return Json{{"bytes", bytes.size()}, {"sha256", co::sha256_file(file.string()).value()}};
}
std::string write_json(const std::filesystem::path& path, const Json& j) {
  std::ofstream out(path, std::ios::binary);
  out << j.dump(2) << '\n';
  out.close();
  if (!out) throw std::runtime_error("fixture JSON");
  return co::sha256_file(path.string()).value();
}
template <class T> std::vector<T> read_all(const std::filesystem::path& path) {
  std::ifstream in(path, std::ios::binary | std::ios::ate);
  std::vector<T> out(static_cast<usize>(in.tellg()) / sizeof(T));
  in.seekg(0);
  // SAFETY: char reads the object representation of a trivially copyable array.
  in.read(reinterpret_cast<char*>(out.data()),
          static_cast<std::streamsize>(out.size() * sizeof(T)));
  return out;
}
// An engine-conformant research role (read_strategy_role's contract) on the fitter fixture's
// arrays over kRoleDates daily sessions from 2018-06-01, members from session 63 on, score
// window [383, kRoleDates): 35 decisions.
constexpr usize kRoleDates = 420, kScoreBegin = 383;
constexpr i64 kDayNs = 86'400'000'000'000LL;
struct Role {
  std::string path, sha;
  Json manifest;
};
Role write_role(const std::filesystem::path& dir, const Fixture& f) {
  if (!std::filesystem::create_directory(dir)) throw std::runtime_error("role directory");
  std::vector<i64> sessions(kRoleDates);
  for (usize t = 0; t < kRoleDates; ++t) sessions[t] = (17683 + static_cast<i64>(t)) * kDayNs;
  std::vector<u64> ids(kN);
  for (usize i = 0; i < kN; ++i) ids[i] = 1000 + 7 * i;
  Json files;
  files["sessions.i64"] = payload(dir / "sessions.i64", sessions);
  files["ids.u64"] = payload(dir / "ids.u64", ids);
  files["close.f64"] = payload(dir / "close.f64", f.close);
  files["raw_close.f64"] = payload(dir / "raw_close.f64", f.raw);
  files["volume.f64"] = payload(dir / "volume.f64", f.volume);
  files["present.u8"] = payload(dir / "present.u8", f.present);
  files["member.u8"] = payload(dir / "member.u8", f.member);
  const Json membership{{"rule", "research-prior63-usd-adv-topn-v1"}, {"top_n", kN},
      {"lookback_sessions", 63}, {"lag_sessions", 1}, {"min_raw_price_exclusive", 5},
      {"min_adv_exclusive", 5000000}, {"ties", "securityID-ascending"},
      {"missing", "complete-prior-calendar-window-required"}, {"common_stock_verified", false}};
  Role role;
  role.manifest = Json{{"schema", "atx.recent-research-role/v1"}, {"status", "complete"},
      {"instrument_namespace", "spiderrock.securityID"}, {"dates", kRoleDates},
      {"instruments", kN}, {"score_begin", kScoreBegin}, {"score_end", kRoleDates},
      {"score_start_ns", sessions[kScoreBegin]}, {"score_end_ns", sessions.back() + kDayNs},
      {"source_sha256", std::string(64, 'a')}, {"membership_recipe", membership.dump()},
      {"clock_recipe", "modeled-session+22h-mark+23h-decision-v1"},
      {"close_basis", "f64(raw-f32-close)*f64-cumulReturnFactor"},
      {"volume_basis", "raw-share-volume"}, {"common_stock_verified", false},
      {"historical_vintage_verified", false},
      {"declared_output_bytes", kRoleDates * kN * 26 + kRoleDates * 8 + kN * 8},
      {"files", std::move(files)}};
  role.path = (dir / "manifest.json").string();
  role.sha = write_json(role.path, role.manifest);
  return role;
}
int dispatch(std::vector<std::string> args, std::ostream& out, std::ostream& err) {
  std::vector<char*> argv;
  for (auto& arg : args) argv.push_back(arg.data());
  return st::dispatch_exposures(static_cast<int>(argv.size()), argv.data(), out, err);
}
Json read_json(const std::filesystem::path& path) {
  std::ifstream in(path);
  return Json::parse(in);
}
} // namespace

// The verb on a pinned engine role: basis.f64 (decisions x names x 4) and forward_returns.f64
// (decisions x names) hold export_decision's bits for [score_begin, score_end - 2), and
// manifest.json (last) their SHAs, the window, the used rows and the refusals.
TEST(Exposures, VerbWritesTheK2Layout) {
  const auto f = fitter_fixture(kRoleDates, 63);
  Directory dir;
  const auto role = write_role(dir.path / "role", f);
  const auto out = dir.path / "export";
  std::ostringstream o, e;
  ASSERT_EQ(dispatch({"exposures", "--role", role.path, "--role-sha256", role.sha, "--output",
                      out.string()}, o, e), 0) << e.str();
  const usize end = kRoleDates - 2, decisions = end - kScoreBegin;
  const auto basis = read_all<f64>(out / "basis.f64");
  const auto forward = read_all<f64>(out / "forward_returns.f64");
  ASSERT_EQ(basis.size(), decisions * kN * kBasis);
  ASSERT_EQ(forward.size(), decisions * kN);
  const auto expected = export_all(f, kScoreBegin, end);
  EXPECT_TRUE(same_bits(basis, expected.basis));
  EXPECT_TRUE(same_bits(forward, expected.forward));
  const auto manifest = read_json(out / "manifest.json");
  EXPECT_EQ(manifest.at("schema"), "atx.price-risk-exposures/v1");
  EXPECT_EQ(manifest.at("status"), "complete");
  EXPECT_EQ(manifest.at("role_manifest_sha256"), role.sha);
  EXPECT_EQ(manifest.at("research_window"), "research-window-v2");
  EXPECT_EQ(manifest.at("decision_begin"), kScoreBegin);
  EXPECT_EQ(manifest.at("decision_end_exclusive"), end);
  EXPECT_EQ(manifest.at("decisions"), decisions);
  EXPECT_EQ(manifest.at("instruments"), kN);
  EXPECT_EQ(manifest.at("ids_sha256"), role.manifest.at("files").at("ids.u64").at("sha256"));
  const auto& files = manifest.at("files");
  EXPECT_EQ(files.at("basis.f64").at("sha256"),
            co::sha256_file((out / "basis.f64").string()).value());
  EXPECT_EQ(files.at("forward_returns.f64").at("sha256"),
            co::sha256_file((out / "forward_returns.f64").string()).value());
  EXPECT_EQ(files.at("basis.f64").at("shape"), Json::array({decisions, kN, kBasis}));
  EXPECT_EQ(files.at("basis.f64").at("bytes"), decisions * kN * kBasis * sizeof(f64));
  ASSERT_EQ(manifest.at("used_rows").size(), decisions);
  usize refused = 0;
  for (usize j = 0; j < decisions; ++j) {
    const auto& decision = expected.decisions[j];
    const bool has_basis = decision.refusal == st::BasisRefusal::None;
    EXPECT_EQ(manifest.at("used_rows")[j], has_basis ? decision.used_rows : usize{0}) << j;
    refused += has_basis ? 0U : 1U;
  }
  EXPECT_EQ(manifest.at("refused").size(), refused);
  EXPECT_NE(o.str().find("exposures: 35 decisions"), std::string::npos) << o.str();
}

// Refusals before any output: a wrong pin, an existing output, a role whose score window
// reaches the research-window seal (no payload is opened), usage errors.
TEST(Exposures, VerbRefusesBeforeAnyOutput) {
  const auto f = fitter_fixture(kRoleDates, 63);
  Directory dir;
  const auto role = write_role(dir.path / "role", f);
  const auto out = dir.path / "never";
  std::ostringstream o, e;
  const auto run = [&](const std::string& path, const std::string& sha) {
    return dispatch({"exposures", "--role", path, "--role-sha256", sha, "--output", out.string()},
                    o, e);
  };
  EXPECT_EQ(run(role.path, std::string(64, 'b')), 1);
  EXPECT_FALSE(std::filesystem::exists(out));
  auto sealed = role.manifest;
  sealed["score_end_ns"] = 1'704'153'600'000'000'000LL; // 2024-01-02
  const auto sealed_path = (dir.path / "role" / "sealed.json").string();
  const auto sealed_sha = write_json(sealed_path, sealed);
  e.str("");
  EXPECT_EQ(run(sealed_path, sealed_sha), 1);
  EXPECT_NE(e.str().find("research-window-v2"), std::string::npos) << e.str();
  EXPECT_FALSE(std::filesystem::exists(out));
  ASSERT_TRUE(std::filesystem::create_directory(out));
  EXPECT_EQ(run(role.path, role.sha), 1);
  EXPECT_TRUE(std::filesystem::is_empty(out));
  EXPECT_EQ(dispatch({"exposures", "--role", role.path, "--output", (dir.path / "x").string()},
                     o, e), 2);
  EXPECT_EQ(dispatch({"exposures", "--role", role.path, "--bogus", "1"}, o, e), 2);
  EXPECT_EQ(dispatch({"exposures", "--max-bytes", "x"}, o, e), 2);
  EXPECT_FALSE(std::filesystem::exists(dir.path / "x"));
}
